export const ARCHETYPES = [
  {
    id: 'maker',
    name: 'Maker',
    kw: ['creëren', 'vrijheid', 'experiment'],
    short: 'Jij maakt. Ideeën krijgen voor jou pas echt waarde als je ze kunt omzetten in iets zichtbaars of tastbaars.',
    motivation: 'Vrijheid om te creëren, te experimenteren en snel iets neer te zetten.',
    energy_from: 'Ruimte om iets nieuws te bedenken, te proberen en direct om te zetten in actie.',
    frustration: 'Te veel regels, trage besluitvorming en omgevingen waarin initiatief wordt afgeremd.',
    strengths: 'Brengt creativiteit, energie en beweging. Zet ideeën om in iets concreets.',
    bricks: 'Flexibele werkplekken, creatieve zones, projecttafels, whiteboards en plekken waar je direct kunt maken, schetsen of testen.',
    bytes: 'Lichte, snelle tools die creatie ondersteunen in plaats van vertragen. Denk aan Miro, Figma, notitietools en eenvoudige samenwerkingsplatforms.',
    behavior: 'Geef richting op hoofdlijnen, maar laat ruimte in de aanpak. Deze persona floreert bij vertrouwen, autonomie en experiment.',
    friction: [
      'Strakke procedures drukken jouw energie omlaag.',
      'Te veel controle voelt als wantrouwen.',
      'Als alles eerst besproken moet worden, zakt jouw initiatief weg.',
    ],
    consequence: [
      'Zonder ruimte om te maken, slaat jouw energie om in frustratie.',
      'Je wordt minder zichtbaar als jouw creatiekracht niet wordt benut.',
      'De organisatie verliest vernieuwing zonder dat iemand het meteen merkt.',
    ],
    leadership: [
      'Geef vrijheid binnen duidelijke kaders.',
      'Stuur op resultaat, niet op ieder stapje.',
      'Maak experimenteren normaal en veilig.',
    ],
    lquote: 'Als je deze persoon te strak aanstuurt, raak je niet de chaos kwijt — maar de creativiteit.',
    mismatch: [
      'Werkplekken zonder maakruimte of visuele hulpmiddelen.',
      'Culturen waarin conformiteit belangrijker is dan initiatief.',
      'Overleggen zonder ruimte om iets uit te proberen.',
    ],
    energycost: [
      'Te veel regels en controle.',
      'Geen ruimte om ideeën te testen.',
      'Steeds moeten wachten op toestemming.',
    ],
    wd: [
      'Creatieve zones met whiteboards en projecttafels',
      'Flexibele werkplekken die meebewegen met het werk',
      'Ruimte om ideeën zichtbaar te maken',
    ],
    ls: [
      'Geef richting, geen dichtgetimmerde instructie',
      'Beloon initiatief zichtbaar',
      'Maak leren door te doen normaal',
    ],
    ct: [
      'Combineert sterk met de Denker',
      'Botst vaak met de Zekerzoeker',
      'Brengt ideeën en energie in het team',
    ],
    cluster: 'creatie',
  },
  {
    id: 'groeier',
    name: 'Groeier',
    kw: ['leren', 'ontwikkeling', 'vooruit'],
    short: 'Jij groeit. Stilstand voelt voor jou niet veilig, maar juist alsof je energie verliest.',
    motivation: 'Nieuwe dingen leren, jezelf ontwikkelen en steeds een stap verder komen.',
    energy_from: 'Uitdaging, feedback, nieuwe ervaringen en zichtbare ontwikkeling.',
    frustration: 'Herhaling, routine en omgevingen waar weinig ruimte is om te leren of te groeien.',
    strengths: 'Leert snel, beweegt mee en stimuleert ook anderen om zich te ontwikkelen.',
    bricks: 'Leerplekken, duo-werkplekken, informele kenniszones en plekken waar coaching en feedback vanzelf ontstaan.',
    bytes: 'Tools die ontwikkeling zichtbaar maken, feedback makkelijk maken en nieuwe kennis toegankelijk houden.',
    behavior: 'Geef perspectief, uitdaging en leerkansen. Laat ontwikkeling onderdeel zijn van het werk zelf.',
    friction: [
      'Zonder uitdaging droogt jouw motivatie snel op.',
      'Weinig feedback voelt voor jou als stilstand.',
      'Als ontwikkeling wordt beloofd maar niet waargemaakt, zakt je vertrouwen.',
    ],
    consequence: [
      'Je blijft wel werken, maar niet meer echt groeien.',
      'De kans neemt toe dat je elders op zoek gaat naar ontwikkeling.',
      'Je energie daalt als je geen toekomst meer voelt.',
    ],
    leadership: [
      'Bespreek leerdoelen actief.',
      'Geef uitdagende opdrachten voor routine.',
      'Maak groei zichtbaar en concreet.',
    ],
    lquote: 'Als je deze persoon niet uitdaagt, verlies je eerst de energie — en daarna de persoon.',
    mismatch: [
      'Functies of teams waarin alles hetzelfde blijft.',
      'Een cultuur zonder feedback.',
      'Omgevingen waarin ontwikkelen alleen bij woorden blijft.',
    ],
    energycost: [
      'Routine zonder uitdaging.',
      'Geen feedback krijgen.',
      'Geen ruimte om te groeien.',
    ],
    wd: [
      'Kennispleinen en informele leerzones',
      'Plekken voor coaching, feedback en uitwisseling',
      'Zichtbare toegang tot inspiratie en nieuwe kennis',
    ],
    ls: [
      'Maak leren onderdeel van het werk',
      'Geef groei taal en richting',
      'Zorg voor regelmatige feedback',
    ],
    ct: [
      'Versterkt de Presteerder goed',
      'Kan Zekerzoekers onrustig maken',
      'Brengt ontwikkeling en beweging in teams',
    ],
    cluster: 'creatie',
  },
  {
    id: 'presteerder',
    name: 'Presteerder',
    kw: ['resultaat', 'tempo', 'grip'],
    short: 'Jij gaat voor resultaat. Je krijgt energie van voortgang, scherpte en iets echt afmaken.',
    motivation: 'Doelen halen, voortgang zien en grip houden op wat ertoe doet.',
    energy_from: 'Heldere doelen, zichtbare voortgang, focus en tastbaar resultaat.',
    frustration: 'Onduidelijkheid, uitstel, eindeloos overleg en teams zonder scherpte.',
    strengths: 'Brengt focus, tempo en resultaat. Helpt teams om niet te blijven hangen.',
    bricks: 'Focusplekken, afgeschermde werkzones, projectruimtes zonder ruis en plekken waar voortgang zichtbaar is.',
    bytes: 'Dashboards, taaktools, planningstools en systemen die direct inzicht geven in doelen, deadlines en voortgang.',
    behavior: 'Wees duidelijk over doelen, verwachtingen en prioriteiten. Geef ruimte, maar houd richting scherp.',
    friction: [
      'Onduidelijkheid remt jouw tempo direct af.',
      'Vergaderen zonder besluit voelt als energieverlies.',
      'Steeds wisselende prioriteiten kosten vertrouwen.',
    ],
    consequence: [
      'Je haakt mentaal af als resultaat te lang uitblijft.',
      'Je levert dan nog wel, maar niet meer op jouw topniveau.',
      'De drive zakt als er geen scherpte meer is.',
    ],
    leadership: [
      'Wees direct en helder.',
      'Erken resultaat expliciet.',
      'Maak prioriteiten zichtbaar en stabiel.',
    ],
    lquote: 'Zonder helder doel gaat deze motor draaien — maar nergens naartoe.',
    mismatch: [
      'Werkplekken zonder focus.',
      'Culturen waarin proces belangrijker is dan resultaat.',
      'Langdurige vaagheid over richting.',
    ],
    energycost: [
      'Onduidelijke doelen.',
      'Vergaderen zonder besluit.',
      'Geen plek voor focus.',
    ],
    wd: [
      'Diepe focuszones',
      'Visuele voortgangsborden',
      'Projectplekken dicht bij stille werkplekken',
    ],
    ls: [
      'Maak prioriteiten concreet',
      'Erken voortgang en output',
      'Stuur op uitkomst, niet op drukte',
    ],
    ct: [
      'Sterk naast de Vernieuwer',
      'Kan botsen met de Verbinder',
      'Houdt teams scherp en in beweging',
    ],
    cluster: 'executie',
  },
  {
    id: 'denker',
    name: 'Denker',
    kw: ['analyse', 'diepgang', 'inhoud'],
    short: 'Jij denkt eerst, dan doe je. Je wilt begrijpen hoe iets werkelijk in elkaar zit voordat je beweegt.',
    motivation: 'Complexiteit doorgronden en kwaliteit brengen op basis van inzicht.',
    energy_from: 'Rust, diepgang, analyse en de ruimte om een vraagstuk echt te begrijpen.',
    frustration: 'Oppervlakkigheid, haast en besluiten zonder inhoudelijke basis.',
    strengths: 'Brengt diepgang, scherpte en kwaliteit. Ziet wat anderen missen.',
    bricks: 'Stille concentratieplekken, focuskamers, bibliotheekachtige zones en omgevingen met zo min mogelijk ruis.',
    bytes: 'Logische systemen, goede documentatie, complete informatie en tools die verdieping ondersteunen.',
    behavior: 'Geef denktijd, inhoud en voorbereiding. Kwaliteit gaat hier vóór snelheid.',
    friction: [
      'Open kantoren zijn voor jou vaak cognitieve ruis.',
      'Besluiten zonder analyse voelen onveilig.',
      'Te veel onderbrekingen maken je minder sterk.',
    ],
    consequence: [
      'Je trekt je terug als diepgang geen plek krijgt.',
      'Jouw inhoudelijke bijdrage verdwijnt stil uit beeld.',
      'Kwaliteit zakt zonder dat het direct zichtbaar is.',
    ],
    leadership: [
      'Geef informatie op tijd en volledig.',
      'Respecteer denktijd.',
      'Waardeer grondigheid zichtbaar.',
    ],
    lquote: 'Wie deze persoon haast, verliest vaak precies datgene wat de kwaliteit bewaakt.',
    mismatch: [
      'Werkvloeren met continue ruis.',
      'Culturen waar snelheid belangrijker is dan inhoud.',
      'Onvoorbereide overleggen zonder scherpe vraag.',
    ],
    energycost: [
      'Onderbrekingen.',
      'Besluiten zonder analyse.',
      'Te weinig rust om te verdiepen.',
    ],
    wd: [
      'Stille focusplekken en akoestische rust',
      'Heldere informatievoorziening',
      'Plekken waar concentratie beschermd wordt',
    ],
    ls: [
      'Geef tijd om te denken',
      'Zorg voor goede voorbereiding',
      'Bescherm kwaliteit in het proces',
    ],
    ct: [
      'Versterkt de Maker goed',
      'Kan met de Presteerder schuren op tempo',
      'Brengt kwaliteit en diepte in teams',
    ],
    cluster: 'reflectie',
  },
  {
    id: 'verbinder',
    name: 'Verbinder',
    kw: ['mensen', 'contact', 'samenhang'],
    short: 'Jij verbindt. Voor jou ontstaat goed werk pas echt als mensen zich gezien en verbonden voelen.',
    motivation: 'Menselijk contact, samenwerking en een sfeer waarin mensen elkaar echt vinden.',
    energy_from: 'Ontmoeting, samenwerking, afstemming en betekenisvol contact.',
    frustration: 'Isolement, afstand, sfeerbreuk en werken zonder echte verbinding.',
    strengths: 'Brengt mensen samen, voelt de onderstroom aan en houdt samenwerking menselijk.',
    bricks: 'Ontmoetingsplekken, koffiecorners, open samenwerkzones en routing die toevallige ontmoeting stimuleert.',
    bytes: 'Communicatietools die menselijk voelen en echt contact makkelijk maken.',
    behavior: 'Maak ruimte voor contact, relatie en afstemming. Verbinding is geen bijzaak maar voorwaarde.',
    friction: [
      'Te veel digitale afstand kost je energie.',
      'Een koude, taakgerichte sfeer maakt je minder sterk.',
      'Als ontmoeting geen plek krijgt, droogt samenwerking op.',
    ],
    consequence: [
      'Je ziet vaak als eerste waar het schuurt.',
      'Zonder verbinding wordt het team stiller en afstandelijker.',
      'Belangrijke signalen worden gemist als jij geen ruimte krijgt.',
    ],
    leadership: [
      'Maak bewust tijd voor contact.',
      'Betrek deze persona vroeg bij verandering.',
      'Zorg dat ontmoeting mogelijk en normaal is.',
    ],
    lquote: 'Een team zonder verbinder merkt pas wat er ontbreekt als iedereen nog wel samenwerkt, maar niemand meer verbonden is.',
    mismatch: [
      'Werkplekken die alleen op focus zijn ingericht.',
      'Teams die alleen digitaal contact hebben.',
      'Culturen waar relatie ondergeschikt is aan taak.',
    ],
    energycost: [
      'Alleen werken zonder contact.',
      'Geen ruimte voor gesprek.',
      'Te veel afstand in samenwerking.',
    ],
    wd: [
      'Warme ontmoetingszones',
      'Informele overlegplekken',
      'Routing die spontane ontmoeting ondersteunt',
    ],
    ls: [
      'Vraag hoe het echt gaat',
      'Maak ontmoeting onderdeel van het werk',
      'Gebruik deze persona als signaalgever',
    ],
    ct: [
      'Sterk naast de Teamspeler',
      'Kan schuren met de Presteerder',
      'Bewaakt de menselijke kant van samenwerking',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'teamspeler',
    name: 'Teamspeler',
    kw: ['loyaliteit', 'vertrouwen', 'samen winnen'],
    short: 'Jij werkt voor het team. Voor jou telt niet alleen wat jij bereikt, maar vooral wat jullie samen neerzetten.',
    motivation: 'Bijdragen aan een vaste groep met vertrouwen, continuïteit en gezamenlijk succes.',
    energy_from: 'Samenwerken met bekende mensen, duidelijke rollen en een sterk teamgevoel.',
    frustration: 'Wisselende teams, onduidelijke verhoudingen en gebrek aan loyaliteit.',
    strengths: 'Brengt rust, loyaliteit en samenwerking. Houdt teams bij elkaar.',
    bricks: 'Vaste teamplekken, herkenbare zones en omgevingen waarin een team zich echt als team kan organiseren.',
    bytes: 'Gedeelde systemen, teamoverzichten, vaste processen en tools die samenwerking voorspelbaar maken.',
    behavior: 'Werk met ritme, helderheid en gezamenlijke afspraken. Deze persona floreert in continuïteit.',
    friction: [
      'Wisselende teams voelen als structurele onrust.',
      'Geen thuisbasis maakt jou minder stevig.',
      'Te weinig aandacht voor teamgevoel maakt jouw kracht onzichtbaar.',
    ],
    consequence: [
      'Je loyaliteit neemt af als het teamfundament ontbreekt.',
      'Onrust vertaalt zich in lagere betrokkenheid.',
      'De samenhang verdwijnt als continuïteit ontbreekt.',
    ],
    leadership: [
      'Wees voorspelbaar en consistent.',
      'Kondig veranderingen op tijd aan.',
      'Maak teamdynamiek bespreekbaar.',
    ],
    lquote: 'Als je het team als wisselgeld behandelt, verliest deze persoon zijn fundament.',
    mismatch: [
      'Hot-desking en continu wisselende groepen.',
      'Een cultuur waarin iedereen vooral voor zichzelf werkt.',
      'Te veel reorganisatie zonder bedding.',
    ],
    energycost: [
      'Wisselende teams.',
      'Geen vaste basis.',
      'Onzekerheid in samenwerking.',
    ],
    wd: [
      'Vaste teamplekken',
      'Herkenbare zones voor teams',
      'Rituelen en routines verankerd in de ruimte',
    ],
    ls: [
      'Bescherm teamcontinuïteit',
      'Zorg voor duidelijkheid in rollen',
      'Betrek het team in veranderingen',
    ],
    ct: [
      'Sterk naast de Verbinder',
      'Kan onrustig worden van de Vernieuwer',
      'Brengt stabiliteit in samenwerking',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'zekerzoeker',
    name: 'Zekerzoeker',
    kw: ['structuur', 'rust', 'duidelijkheid'],
    short: 'Jij zorgt dat het klopt. Duidelijkheid, structuur en voorspelbaarheid maken jou sterk.',
    motivation: 'Overzicht, stabiliteit en weten waar je aan toe bent.',
    energy_from: 'Heldere verwachtingen, structuur, rust en een voorspelbare omgeving.',
    frustration: 'Chaos, last-minute wijzigingen en onduidelijkheid.',
    strengths: 'Brengt rust, betrouwbaarheid en proceskwaliteit. Ziet snel waar het niet klopt.',
    bricks: 'Vaste werkplekken, duidelijke zones, overzichtelijke routing en zo min mogelijk onnodige verandering.',
    bytes: 'Heldere systemen, stabiele processen en betrouwbare informatie.',
    behavior: 'Communiceer vroeg, helder en consistent. Deze persona heeft voorspelbaarheid nodig om goed te functioneren.',
    friction: [
      'Onduidelijkheid is voor jou geen kleine irritatie, maar een echte blokkade.',
      'Last-minute wijzigingen kosten jou disproportioneel veel energie.',
      'Te veel verandering tegelijk haalt jouw stabiliteit weg.',
    ],
    consequence: [
      'Chronische onduidelijkheid leidt tot spanning.',
      'Je levert minder goed als je steeds moet schakelen zonder houvast.',
      'Weerstand groeit als helderheid verdwijnt.',
    ],
    leadership: [
      'Communiceer vroeg en volledig.',
      'Maak verwachtingen expliciet.',
      'Bied structuur in onzekere periodes.',
    ],
    lquote: 'Onduidelijkheid is voor deze persoon geen uitdaging, maar een aantasting van werkvermogen.',
    mismatch: [
      'Omgevingen met continue verandering.',
      'Vage verwachtingen of incomplete informatie.',
      'Werkplekken zonder vaste ankers.',
    ],
    energycost: [
      'Onvoorspelbaarheid.',
      'Te veel verandering.',
      'Onduidelijke kaders.',
    ],
    wd: [
      'Vaste ankerplekken',
      'Rustige, overzichtelijke inrichting',
      'Duidelijke structuren en voorspelbare zones',
    ],
    ls: [
      'Geef helderheid vroeg',
      'Behandel structuur als kwaliteit',
      'Respecteer de behoefte aan voorspelbaarheid',
    ],
    ct: [
      'Sterke basis naast de Presteerder',
      'Botst vaak met de Maker',
      'Brengt rust en betrouwbaarheid',
    ],
    cluster: 'structuur',
  },
  {
    id: 'vernieuwer',
    name: 'Vernieuwer',
    kw: ['vooruitdenken', 'kansen', 'verandering'],
    short: 'Jij ziet wat anders kan. Voor jou is verandering niet vooral risico, maar vooral potentie.',
    motivation: 'Kansen zien, beweging creëren en bouwen aan iets dat beter kan.',
    energy_from: 'Nieuwe ideeën, beweging, verandering en een blik op de toekomst.',
    frustration: 'Stilstand, behoudzucht en organisaties zonder visie.',
    strengths: 'Brengt richting, vernieuwing en toekomstgericht denken.',
    bricks: 'Inspirerende werkplekken, innovatiezones, projectruimtes en omgevingen die beweging en vernieuwing zichtbaar maken.',
    bytes: 'Tools voor innovatie, experimenteren, trends en snelle iteratie.',
    behavior: 'Geef ruimte voor ideeën, strategie en verkenning. Betrek deze persona in verandering en koers.',
    friction: [
      'Sturen op alleen de korte termijn knelt voor jou direct.',
      'Bureaucratie voelt voor jou als energielek.',
      'Als ideeën nooit landen, stop jij met delen.',
    ],
    consequence: [
      'Je wordt stiller als vernieuwing geen podium krijgt.',
      'De organisatie verliest zicht op toekomstige kansen.',
      'Jouw energie verschuift naar plekken waar wel beweging is.',
    ],
    leadership: [
      'Geef strategische ruimte.',
      'Verbind visie aan concrete experimenten.',
      'Zie deze persona als mede-ontwerper.',
    ],
    lquote: 'Zonder podium bouwt deze persoon zijn eigen podium — en dat is zelden binnen dezelfde organisatie.',
    mismatch: [
      'Omgevingen zonder ruimte voor vernieuwing.',
      'Besluitvorming die vernieuwing steeds vertraagt.',
      'Culturen zonder toekomstperspectief.',
    ],
    energycost: [
      'Geen ruimte voor ideeën.',
      'Trage besluitvorming.',
      'Vastzitten in oude patronen.',
    ],
    wd: [
      'Inspirerende innovatiezones',
      'Plekken waar toekomstgericht werk zichtbaar is',
      'Ruimte voor experiment en beweging',
    ],
    ls: [
      'Geef visie en mandaat',
      'Verbind ideeën aan actie',
      'Gebruik deze persona bij strategie en transitie',
    ],
    ct: [
      'Sterk naast de Presteerder',
      'Kan Zekerzoekers destabiliseren',
      'Motor van verandering in teams',
    ],
    cluster: 'creatie',
  },
];

export const QUESTIONS = [
  {
    q: 'Waar krijg jij energie van op een werkdag?',
    a: [
      'Iets nieuws bedenken en gewoon beginnen, ook zonder plan',
      'Mezelf ontwikkelen en nieuwe dingen leren',
      'Dingen afronden en echt resultaat zien',
      'Me volledig vastbijten in een complex vraagstuk',
      'Rust, stabiliteit en een fijne werksfeer',
      'Samenwerken met mensen waar ik op kan bouwen',
      'Weten wat er van mij verwacht wordt en dat rustig uitvoeren',
      'Kansen zien die anderen nog niet zien — en daarop inspelen',
    ],
  },
  {
    q: 'Hoe werk jij het liefst?',
    a: [
      'Ik volg mijn eigen ideeën en bepaal graag zelf hoe ik iets aanpak',
      'Ik wil groeien, leren en steeds beter worden in wat ik doe',
      'Ik werk het liefst doelgericht naar een concreet eindresultaat toe',
      'Ik wil eerst begrijpen hoe iets echt in elkaar zit',
      'Ik werk het beste als er aandacht is voor sfeer en verbinding',
      'Ik werk graag samen met mensen die ik goed ken en vertrouw',
      'Ik werk het liefst met duidelijke structuur en planning',
      'Ik krijg energie van verandering en nieuwe mogelijkheden',
    ],
  },
  {
    q: 'Waar loop jij op leeg?',
    a: [
      'Te veel regels en te weinig ruimte om iets uit te proberen',
      'Geen kans krijgen om jezelf verder te ontwikkelen',
      'Geen resultaat zien van wat je doet',
      'Oppervlakkigheid en te weinig inhoud',
      'Werken zonder echt contact of verbinding',
      'Steeds wisselende mensen en geen vast teamgevoel',
      'Chaos, onduidelijkheid en last-minute veranderingen',
      'Stilstand en vasthouden aan hoe het altijd ging',
    ],
  },
  {
    q: 'Wat typeert jou het meest?',
    a: [
      'Ik ben creatief, praktisch en zet ideeën snel om in iets concreets',
      'Ik ben leergierig en wil mezelf blijven ontwikkelen',
      'Ik ben scherp op doelen en wil dingen echt afmaken',
      'Ik ben analytisch en wil eerst snappen voordat ik handel',
      'Ik voel sfeer en mensen goed aan',
      'Ik ben loyaal en werk graag voor het team',
      'Ik ben gestructureerd en betrouwbaar',
      'Ik zie snel wat beter of anders kan',
    ],
  },
  {
    q: 'Hoe neem jij het liefst beslissingen?',
    a: [
      'Door te voelen wat werkt en daar iets van te maken',
      'Door te kijken wat ik hiervan kan leren',
      'Door te focussen op wat het meeste resultaat oplevert',
      'Door eerst goed te analyseren wat klopt',
      'Door af te stemmen met anderen en te voelen wat nodig is',
      'Door rekening te houden met het team en de onderlinge samenwerking',
      'Door te kiezen voor duidelijkheid en voorspelbaarheid',
      'Door te kijken welke kans of beweging hier in zit',
    ],
  },
  {
    q: 'Wat geeft jou het meeste voldoening?',
    a: [
      'Iets maken wat er eerst nog niet was',
      'Merken dat je zelf groeit en sterker wordt',
      'Een doel halen waar je naartoe hebt gewerkt',
      'Iets echt begrijpen en doorgronden',
      'Een goed gesprek of een fijne samenwerking',
      'Samen met anderen iets neerzetten als team',
      'Rust, overzicht en weten dat het klopt',
      'Een nieuwe richting of kans zien ontstaan',
    ],
  },
  {
    q: 'Hoe start jij aan iets nieuws?',
    a: [
      'Ik begin liever meteen en stuur onderweg wel bij',
      'Ik zie het als kans om te leren',
      'Ik wil snel weten wat het doel is en hoe ik daar kom',
      'Ik wil eerst alle kanten van het vraagstuk begrijpen',
      'Ik zoek eerst afstemming met anderen',
      'Ik kijk eerst met wie ik dit samen doe',
      'Ik wil eerst weten wat de kaders en verwachtingen zijn',
      'Ik kijk meteen welke nieuwe mogelijkheid hierin zit',
    ],
  },
  {
    q: 'Wat zoek jij in een werkomgeving?',
    a: [
      'Vrijheid, flexibiliteit en ruimte om te creëren',
      'Uitdaging, inspiratie en ontwikkelkansen',
      'Focus, tempo en resultaatgerichtheid',
      'Rust, concentratie en inhoudelijke diepgang',
      'Ontmoeting, menselijkheid en contact',
      'Een herkenbare plek met een vertrouwde groep',
      'Duidelijkheid, overzicht en voorspelbaarheid',
      'Een inspirerende omgeving waar vernieuwing voelbaar is',
    ],
  },
  {
    q: 'Wat waardeer jij het meest in samenwerking?',
    a: [
      'Ruimte voor eigen ideeën en initiatief',
      'Dat we van elkaar leren en ons ontwikkelen',
      'Dat we tempo maken en echt iets neerzetten',
      'Dat besluiten inhoudelijk kloppen',
      'Dat er aandacht is voor de mens achter het werk',
      'Dat we op elkaar kunnen rekenen als team',
      'Dat rollen en verwachtingen helder zijn',
      'Dat we samen richting geven aan iets nieuws',
    ],
  },
  {
    q: 'Wat frustreert jou het meest in een team?',
    a: [
      'Als ideeën direct worden dichtgeregeld',
      'Als niemand zich ontwikkelt of iets nieuws leert',
      'Als er veel gepraat wordt maar weinig gebeurt',
      'Als snelheid belangrijker wordt dan kwaliteit',
      'Als de menselijke kant wordt genegeerd',
      'Als iedereen vooral voor zichzelf werkt',
      'Als afspraken vaag blijven of steeds veranderen',
      'Als vernieuwing wordt tegengehouden door oude patronen',
    ],
  },
  {
    q: 'Hoe ga jij om met verandering?',
    a: [
      'Ik gebruik het als ruimte om iets nieuws te proberen',
      'Ik kijk wat ik hiervan kan leren',
      'Ik wil snel weten wat dit betekent voor resultaat en planning',
      'Ik wil eerst begrijpen wat er precies verandert',
      'Ik let op wat het met mensen doet',
      'Ik kijk vooral wat dit betekent voor het team',
      'Ik word onrustig als het te snel of te vaag gaat',
      'Ik krijg juist energie van verandering en nieuwe beweging',
    ],
  },
  {
    q: 'Wat motiveert jou het meest?',
    a: [
      'Vrijheid om iets op mijn manier te maken',
      'Ontwikkeling en het gevoel dat ik groei',
      'Voortgang, grip en resultaat',
      'Inhoud, inzicht en kwaliteit',
      'Verbinding en betekenisvol contact',
      'Een sterk teamgevoel en gezamenlijke verantwoordelijkheid',
      'Zekerheid, duidelijkheid en overzicht',
      'Vernieuwing, kansen en toekomstgericht denken',
    ],
  },
  {
    q: 'Wat is jouw kracht in een team?',
    a: [
      'Ik breng ideeën tot leven',
      'Ik breng ontwikkeling en leerenergie',
      'Ik breng focus en resultaat',
      'Ik breng analyse en diepgang',
      'Ik breng verbinding tussen mensen',
      'Ik breng samenwerking en loyaliteit',
      'Ik breng structuur en betrouwbaarheid',
      'Ik breng vernieuwing en richting',
    ],
  },
  {
    q: 'Wat heb jij nodig van een leidinggevende?',
    a: [
      'Ruimte en vertrouwen om zelf vorm te geven',
      'Aandacht voor mijn groei en ontwikkeling',
      'Duidelijke doelen en scherpe prioriteiten',
      'Inhoudelijke voorbereiding en denktijd',
      'Menselijke aandacht en echte betrokkenheid',
      'Stabiliteit en aandacht voor het team',
      'Helderheid, voorspelbaarheid en duidelijke afspraken',
      'Visie, lef en ruimte voor verandering',
    ],
  },
  {
    q: 'Wanneer voelt een werkdag voor jou geslaagd?',
    a: [
      'Als ik iets heb gemaakt of in beweging heb gezet',
      'Als ik iets geleerd heb en verder ben gekomen',
      'Als ik concreet resultaat heb geboekt',
      'Als ik iets ingewikkelds echt ben gaan begrijpen',
      'Als er goed contact of fijne afstemming was',
      'Als we het samen goed hebben gedaan als team',
      'Als er rust, overzicht en duidelijkheid was',
      'Als ik een nieuwe kans of richting heb gezien',
    ],
  },
  {
    q: 'Wat zegt het meest over hoe jij werkt?',
    a: [
      'Ik werk graag vrij en creatief',
      'Ik werk graag lerend en in ontwikkeling',
      'Ik werk graag doelgericht en scherp',
      'Ik werk graag verdiepend en inhoudelijk',
      'Ik werk graag mensgericht en verbindend',
      'Ik werk graag loyaal en samen met een vaste groep',
      'Ik werk graag gestructureerd en voorspelbaar',
      'Ik werk graag vernieuwend en toekomstgericht',
    ],
  },
];