export const ARCHETYPES = [
  {
    id: 'maker',
    name: 'Maker',
    kw: ['creëren', 'experimenteren', 'vrijheid'],
    short: 'Jij maakt. Ideeën zijn voor jou pas waardevol als ze zichtbaar worden.',
    motivation: 'Vrijheid om te creëren, te experimenteren en snel iets neer te zetten.',
    energy_from: 'Vrijheid om te creëren, experimenteren en ideeën direct om te zetten naar iets tastbaars.',
    frustration: 'Strakke processen, micromanagement en omgevingen waar weinig ruimte is voor initiatief.',
    strengths: 'Brengt originaliteit, energie en beweging. Zet ideeën om in iets tastbaars.',
    bricks: 'Flexibele werkplekken, projecttafels en plekken waar je direct iets kunt maken. Denk aan aanlandplekken, creatieve zones, whiteboards, visuele zones en prototyping-ruimtes.',
    bytes: 'Snelle, intuïtieve tools die het creatieve proces ondersteunen in plaats van vertragen. Denk aan Miro, Figma of lichte samenwerkingstools waarmee je snel kunt schetsen, delen en aanpassen.',
    behavior: 'Geef vrijheid in aanpak en stuur op resultaat. Vertrouwen en autonomie zorgen hier voor energie en eigenaarschap.',
    friction: [
      'Vaste werkplekken en strakke procedures drukken jouw energie omlaag.',
      'Als de cultuur uitvoering belangrijker maakt dan ideeën, raak jij eigenaarschap kwijt.',
      'Micromanagement voelt voor jou als wantrouwen.',
    ],
    consequence: [
      'Jouw energie slaat om in frustratie als er te weinig ruimte is om te maken.',
      'Als je geen speelruimte voelt, ga je die elders zoeken.',
      'Wat overblijft is iemand die aanwezig is, maar niet meer echt aan staat.',
    ],
    leadership: [
      'Geef richting op doelniveau en laat de aanpak vrij.',
      'Spreek over resultaat, niet over elk tussenstapje.',
      'Beloon initiatief zichtbaar en maak experimenteren normaal.',
    ],
    lquote: 'Als je deze persoon te strak aanstuurt, raak je niet de chaos kwijt — maar de creativiteit.',
    mismatch: [
      'Werkplekken zonder maakruimte remmen jouw natuurlijke manier van werken.',
      'Kantoren zonder focus- én experimenteerzones maken goed werken moeilijk.',
      'Culturen die conformiteit belonen boven eigenaarschap.',
    ],
    energycost: [
      'Vaste werkplekken zonder flexibiliteit.',
      'Te veel regels en controle.',
      'Geen ruimte om ideeën te testen.',
    ],
    wd: [
      'Maakruimtes en labzones naast concentratieplekken',
      'Whiteboards en prototypemateriaal altijd beschikbaar',
      'Geen vaste zitplaats — de plek volgt het werk',
    ],
    ls: [
      'Geef richting, geen instructie',
      'Bespreek resultaat, niet de route',
      'Maak experimenteren en leren van fouten bespreekbaar',
    ],
    ct: [
      'Combineert sterk met de Denker',
      'Structurele spanning met de Zekerzoeker',
      'Laat deze persona ideeën visualiseren voor het team',
    ],
    cluster: 'creatie',
  },
  {
    id: 'groeier',
    name: 'Groeier',
    kw: ['ontwikkelen', 'leren', 'vooruit'],
    short: 'Jij groeit. Stilstand is voor jou geen comfort, maar verlies.',
    motivation: 'Zich ontwikkelen, nieuwe vaardigheden opbouwen en steeds een volgende stap zetten.',
    energy_from: 'Nieuwe dingen leren, feedback krijgen en zichzelf continu ontwikkelen.',
    frustration: 'Stagnatie, herhaling en omgevingen waar weinig ruimte is om te groeien.',
    strengths: 'Leert snel, beweegt mee en trekt anderen mee in ontwikkeling.',
    bricks: 'Leerplekken, duo-werkplekken en informele kenniszones. Denk aan plekken voor uitwisseling, kennisdeling en korte feedbackmomenten.',
    bytes: 'Systemen die ontwikkeling zichtbaar maken, feedback makkelijk maken en toegang geven tot nieuwe kennis en inspiratie. Denk aan leerplatforms, feedbacktools en kennisbanken.',
    behavior: 'Geef perspectief, uitdaging en ontwikkelruimte. Zorg dat leren onderdeel is van het werk, niet iets extra’s.',
    friction: [
      'Als alles hetzelfde blijft, slaat jouw energie om in onrust.',
      'Weinig feedback voelt voor jou als desinteresse.',
      'Ontwikkeling beloven maar niets mogelijk maken tast je motivatie aan.',
    ],
    consequence: [
      'Zonder groei droogt jouw motivatie langzaam op.',
      'Jij vertrekt vaak eerder dan anderen als er geen perspectief meer is.',
      'Wat achterblijft is iemand die wel werkt, maar niet meer ontwikkelt.',
    ],
    leadership: [
      'Bespreek actief leerdoelen en niet alleen output.',
      'Geef uitdagende opdrachten vóór routinetaken.',
      'Maak leren praktisch en laagdrempelig mogelijk.',
    ],
    lquote: 'Als je deze persoon niet uitdaagt, verlies je eerst de energie — en daarna de persoon.',
    mismatch: [
      'Functies met weinig variatie voelen als stilstand.',
      'Senioriteit belonen boven nieuwsgierigheid werkt demotiverend.',
      'Weinig feedback voelt als: jij doet er niet toe.',
    ],
    energycost: [
      'Routine zonder uitdaging.',
      'Geen feedback krijgen.',
      'Geen ontwikkelmogelijkheden.',
    ],
    wd: [
      'Kennispleinen en informele leerhoeken',
      'Duo-werkplekken voor feedback en kennisoverdracht',
      'Toegang tot externe prikkels en inspiratie',
    ],
    ls: [
      'Bespreek leerdoelen actief',
      'Geef uitdaging vóór routine',
      'Maak ontwikkeling zichtbaar en concreet',
    ],
    ct: [
      'Groeit sterk naast de Presteerder',
      'Kan de Zekerzoeker onrustig maken',
      'Motor voor teamontwikkeling',
    ],
    cluster: 'creatie',
  },
  {
    id: 'presteerder',
    name: 'Presteerder',
    kw: ['doelen halen', 'grip', 'resultaat'],
    short: 'Jij gaat voor resultaat. Doelen zijn er om gehaald te worden.',
    motivation: 'Doelen halen, voortgang zien en grip houden op wat telt.',
    energy_from: 'Heldere doelen, zichtbare voortgang en het behalen van resultaat.',
    frustration: 'Onduidelijkheid, trage besluitvorming en vergaderingen zonder uitkomst.',
    strengths: 'Brengt focus, tempo en resultaat. Houdt het team scherp op wat ertoe doet.',
    bricks: 'Stille focusplekken en resultaatgerichte werkzones. Denk aan afgeschermde werkplekken, duidelijke zones voor geconcentreerd werk en projectruimtes zonder afleiding.',
    bytes: 'Dashboards, taaktools en systemen die prioriteiten, deadlines en voortgang direct zichtbaar maken.',
    behavior: 'Wees duidelijk over doelen en prioriteiten. Geef eigenaarschap en stuur op resultaat.',
    friction: [
      'Onduidelijke doelen leggen jouw werk stil.',
      'Steeds schuivende prioriteiten kosten vertrouwen.',
      'Vergaderen zonder besluit voelt als verspilde energie.',
    ],
    consequence: [
      'Jouw frustratie wordt zichtbaar in tempo en houding.',
      'Als grip verdwijnt, zakt je motivatie snel weg.',
      'Wat overblijft is iemand die levert op minimum in plaats van op potentieel.',
    ],
    leadership: [
      'Wees direct en helder, ook als niet alles perfect uitgewerkt is.',
      'Erken resultaat expliciet.',
      'Geef vrijheid in aanpak, maar laat richting nooit vaag.',
    ],
    lquote: 'Zonder helder doel gaat deze motor draaien — maar nergens naartoe.',
    mismatch: [
      'Werkplekken zonder focusmogelijkheden drukken jouw productiviteit.',
      'Processen boven resultaten zetten frustreert je structureel.',
      'Trage besluitvorming remt jouw energie direct af.',
    ],
    energycost: [
      'Onduidelijke doelen.',
      'Vergaderen zonder besluit.',
      'Gebrek aan focusplekken.',
    ],
    wd: [
      'Diepe focuszones met minimale afleiding',
      'Visuele voortgangsborden',
      'Samenwerkplekken dicht bij stille zones',
    ],
    ls: [
      'Wees direct in verwachtingen',
      'Erken resultaat expliciet',
      'Geef autonomie; stuur op richting',
    ],
    ct: [
      'Sterk naast de Vernieuwer',
      'Kan de Verbinder frustreren',
      'Brengt de drive die het team scherp houdt',
    ],
    cluster: 'executie',
  },
  {
    id: 'denker',
    name: 'Denker',
    kw: ['begrijpen', 'structuur', 'inhoud'],
    short: 'Jij denkt eerst, dan doe je. Diepgang gaat voor snelheid.',
    motivation: 'Complexiteit begrijpen en kwaliteit brengen voordat er gehandeld wordt.',
    energy_from: 'Rust, analyse en de tijd om complexe vraagstukken echt te doorgronden.',
    frustration: 'Oppervlakkigheid, ruis en beslissingen zonder onderbouwing.',
    strengths: 'Brengt diepgang, precisie en kwaliteit. Ziet wat anderen missen.',
    bricks: 'Stille concentratieplekken en afgesloten ruimtes. Denk aan focuskamers, bibliotheekachtige werkplekken, akoestische rust en overzicht.',
    bytes: 'Logische systemen, complete informatie, documentatie en kennisstructuren die verdieping mogelijk maken.',
    behavior: 'Geef tijd om te denken en zorg voor goede voorbereiding. Kwaliteit boven snelheid.',
    friction: [
      'Open kantoren zijn voor jou vaak pure cognitieve ruis.',
      'Culturen die snelheid boven kwaliteit zetten, knellen direct.',
      'Vergaderingen zonder agenda voelen intellectueel onveilig.',
    ],
    consequence: [
      'Als diepgang niet meer kan, trek jij je terug.',
      'Jouw kennis verdwijnt dan stilletjes uit het gesprek.',
      'De kwaliteitsrem valt weg zonder dat iemand het meteen merkt.',
    ],
    leadership: [
      'Geef informatie op tijd en volledig.',
      'Respecteer denktijd en verwacht niet altijd direct een antwoord.',
      'Waardeer grondigheid, ook als het tempo tijdelijk lager ligt.',
    ],
    lquote: 'Wie deze persoon haast, verliest vaak precies datgene wat de kwaliteit bewaakt.',
    mismatch: [
      'Open werkvloeren met veel ruis en onderbrekingen.',
      'Besluiten onder tijdsdruk zonder inhoudelijke basis.',
      'Snelheid verwarren met kwaliteit.',
    ],
    energycost: [
      'Open kantoor met veel prikkels.',
      'Onderbrekingen.',
      'Besluiten zonder analyse.',
    ],
    wd: [
      'Stille zones met akoestische afscherming',
      'Bibliotheekachtige concentratieplekken',
      'Individuele werkruimtes voor verdieping',
    ],
    ls: [
      'Geef informatie op tijd',
      'Respecteer denktijd',
      'Waardeer grondigheid ook als het vertraagt',
    ],
    ct: [
      'Aanvulling op de Maker',
      'Kan botsen met de Presteerder over tempo',
      'Bewaker van kwaliteit',
    ],
    cluster: 'reflectie',
  },
  {
    id: 'verbinder',
    name: 'Verbinder',
    kw: ['mensen', 'energie', 'samen'],
    short: 'Jij verbindt. Mensen laten samenwerken is jouw kracht.',
    motivation: 'Menselijk contact, vertrouwen en samenwerking die verder gaat dan taakverdeling.',
    energy_from: 'Contact, samenwerking en het gevoel dat mensen echt verbonden zijn.',
    frustration: 'Isolement, afstand en werken zonder menselijk contact.',
    strengths: 'Brengt mensen samen, voelt de onderstroom aan en houdt samenwerking menselijk.',
    bricks: 'Ontmoetingsplekken, koffiecorners en open samenwerkzones. Denk aan warme ontmoetingsplekken, informele zones en routing die toevallige ontmoetingen uitlokt.',
    bytes: 'Communicatietools die verbinding makkelijk en menselijk maken. Denk aan chat, video en informele kanalen.',
    behavior: 'Maak ruimte voor contact en afstemming. Relatie is hier net zo belangrijk als resultaat.',
    friction: [
      'Hybride werken zonder verbindingsrituelen voelt voor jou als verlies.',
      'Een cultuur die contact minimaliseert haalt jouw energie weg.',
      'Als de omgeving geen ontmoeting uitlokt, droogt samenwerking op.',
    ],
    consequence: [
      'Jij merkt vaak als eerste wat er speelt — maar alleen als je erbij kunt zijn.',
      'Zonder verbinding wordt het team stiller en afstandelijker.',
      'De vroege signalen van gedoe verdwijnen als jij geen plek krijgt.',
    ],
    leadership: [
      'Maak bewust tijd voor persoonlijk contact.',
      'Betrek deze persona vroeg bij verandering en samenwerking.',
      'Zorg dat ontmoeting geen toeval is, maar mogelijk gemaakt wordt.',
    ],
    lquote: 'Een team zonder verbinder merkt pas wat er ontbreekt als iedereen nog wel samenwerkt, maar niemand meer verbonden is.',
    mismatch: [
      'Werkplekken die alleen op focus zijn ingericht.',
      'Digitale communicatie als enige vorm van contact.',
      'Hybride roosters zonder ritme of rituelen.',
    ],
    energycost: [
      'Alleen werken zonder contact.',
      'Te veel digitale afstand.',
      'Geen ruimte voor gesprek.',
    ],
    wd: [
      'Warme ontmoetingszones',
      'Kantine als echte ontmoetingsplek',
      'Routing die mensen langs elkaar brengt',
    ],
    ls: [
      'Maak tijd voor het persoonlijke gesprek',
      'Vraag hoe het echt gaat',
      'Betrek vroeg bij verandering',
    ],
    ct: [
      'Onmisbaar naast de Teamspeler',
      'Kan de Presteerder irriteren',
      'Vroeg-signaleerder van teamdynamiek',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'teamspeler',
    name: 'Teamspeler',
    kw: ['vertrouwen', 'vaste groep', 'loyaliteit'],
    short: 'Jij werkt voor het team. Samen winnen is belangrijker dan solo scoren.',
    motivation: 'Bijdragen aan een hechte groep met continuïteit, vertrouwen en heldere rollen.',
    energy_from: 'Samenwerken met een vertrouwd team en duidelijke onderlinge afspraken.',
    frustration: 'Wisselende teams en gebrek aan stabiliteit.',
    strengths: 'Brengt rust, loyaliteit en stabiliteit. Houdt teams bij elkaar.',
    bricks: 'Vaste teamplekken, herkenbare zones en gezamenlijke werkzones. Denk aan plekken waar je met je team zit en samen zichtbaar bent.',
    bytes: 'Gedeelde systemen, teamoverzichten, planningen en vertrouwde processen die samenwerking ondersteunen.',
    behavior: 'Werk met ritme, duidelijkheid en gezamenlijke afspraken. Zorg voor stabiliteit en samenwerking.',
    friction: [
      'Continu wisselende teams voelen voor jou als structurele onrust.',
      'Activiteitengebaseerd werken zonder thuisbasis haalt houvast weg.',
      'Te weinig aandacht voor groepsdynamiek maakt jou onzichtbaar.',
    ],
    consequence: [
      'Als de vaste basis verdwijnt, verdwijnt ook een deel van jouw loyaliteit.',
      'Onzekerheid in het team vertaalt zich in lagere inzet.',
      'Stabiliteit die verloren gaat, krijg je niet zomaar terug.',
    ],
    leadership: [
      'Wees consistent en voorspelbaar.',
      'Kondig veranderingen vroeg aan.',
      'Maak teamdynamiek expliciet onderdeel van het werk.',
    ],
    lquote: 'Als je het team als wisselgeld behandelt, verliest deze persoon zijn fundament.',
    mismatch: [
      'Hot-desking en continu roulerende teams.',
      'Flexibiliteit boven continuïteit zetten.',
      'Voortdurende reorganisaties zonder bedding.',
    ],
    energycost: [
      'Wisselende teams.',
      'Geen vaste werkplek.',
      'Onzekerheid in samenwerking.',
    ],
    wd: [
      'Vaste teamwerkplekken met eigen identiteit',
      'Gedeelde teamruimtes voor vaste groepen',
      'Rituelen verankerd in de fysieke ruimte',
    ],
    ls: [
      'Wees consistent en voorspelbaar',
      'Kondig veranderingen vroeg en volledig aan',
      'Betrek bij teambeslissingen',
    ],
    ct: [
      'Sterk naast de Verbinder',
      'Onrustig van de Vernieuwer',
      'Brengt rust die anderen vaak onderschatten',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'zekerzoeker',
    name: 'Zekerzoeker',
    kw: ['rust', 'duidelijkheid', 'voorspelbaarheid'],
    short: 'Jij zorgt dat het klopt. Duidelijkheid en structuur maken jou sterk.',
    motivation: 'Stabiliteit, overzicht en weten wat er verwacht wordt.',
    energy_from: 'Overzicht, voorspelbaarheid en duidelijke verwachtingen.',
    frustration: 'Onzekerheid, last-minute wijzigingen en chaos.',
    strengths: 'Brengt rust, consistentie en proceskwaliteit. Ziet snel waar het niet klopt.',
    bricks: 'Vaste werkplekken, duidelijke zones en een voorspelbare indeling. Denk aan afgeschermde werkplekken, overzichtelijke routing en zo min mogelijk onverwachte verandering.',
    bytes: 'Heldere systemen, vaste processen en betrouwbare informatie. Denk aan duidelijke afspraken, complete informatie en zo min mogelijk wisselingen tegelijk.',
    behavior: 'Communiceer duidelijk en op tijd. Voorkom verrassingen en geef structuur.',
    friction: [
      'Onduidelijkheid is voor jou geen kleine irritatie, maar een directe belemmering.',
      'Agile omgevingen zonder houvast voelen structureel ongemakkelijk.',
      'Last-minute wijzigingen kosten jou disproportioneel veel energie.',
    ],
    consequence: [
      'Chronische onduidelijkheid leidt bij jou tot chronische spanning.',
      'Als jij je voortdurend moet aanpassen, lever je niet meer je beste werk.',
      'Weerstand groeit zodra helderheid en transparantie verdwijnen.',
    ],
    leadership: [
      'Communiceer vroeg, volledig en consistent.',
      'Bied structuur in onzekere periodes.',
      'Maak verwachtingen en keuzes expliciet.',
    ],
    lquote: 'Onduidelijkheid is voor deze persoon geen uitdaging, maar een aantasting van werkvermogen.',
    mismatch: [
      'Voortdurend heringerichte werkplekken.',
      'Wendbaarheid verwarren met onvoorspelbaarheid.',
      'Te laat gedeelde informatie.',
    ],
    energycost: [
      'Onvoorspelbaarheid.',
      'Te veel verandering.',
      'Onduidelijke verwachtingen.',
    ],
    wd: [
      'Eigen vaste werkplek als anker',
      'Rustige inrichting zonder visuele onrust',
      'Duidelijke routing en voorspelbare indeling',
    ],
    ls: [
      'Communiceer vroeg en volledig',
      'Bied structuur als actief leiderschapsgedrag',
      'Respecteer de behoefte aan overzicht',
    ],
    ct: [
      'Stabiele basis naast de Presteerder',
      'Structurele wrijving met de Maker',
      'Brengt houvast bij richtingloosheid',
    ],
    cluster: 'structuur',
  },
  {
    id: 'vernieuwer',
    name: 'Vernieuwer',
    kw: ['kansen', 'vooruitdenken', 'verandering'],
    short: 'Jij ziet wat anders kan. Verandering is voor jou geen risico, maar kans.',
    motivation: 'Nieuwe kansen zien, verkennen en omzetten in beweging.',
    energy_from: 'Nieuwe ideeën, verandering en het bouwen aan de toekomst.',
    frustration: 'Status quo en organisaties zonder visie.',
    strengths: 'Brengt richting, vernieuwing en een scherp oog voor wat morgen nodig is.',
    bricks: 'Inspirerende werkplekken, innovatiezones en projectruimtes. Denk aan brainstormruimtes, externe prikkels en plekken waar vernieuwing zichtbaar wordt.',
    bytes: 'Tools voor innovatie, trends en experimenteren. Denk aan systemen die snel testen, leren en vernieuwen mogelijk maken.',
    behavior: 'Geef ruimte voor vernieuwing en ideeën. Betrek deze persona in strategische keuzes.',
    friction: [
      'Organisaties die alleen op de korte termijn sturen, knellen voor jou.',
      'Als ideeën steeds niet landen, stop jij met delen.',
      'Bureaucratie is voor jou geen tempovertraging maar een energielek.',
    ],
    consequence: [
      'Zonder ruimte word jij intern stiller of extern zichtbaarder.',
      'Jouw strategische voelsprieten verdwijnen dan uit de organisatie.',
      'De toekomst komt alsnog — alleen zonder dat jij hem hebt helpen ontwerpen.',
    ],
    leadership: [
      'Geef strategische ruimte en een mandaat dat groot genoeg is.',
      'Verbind ideeën aan concrete experimenten en deadlines.',
      'Zie deze persona als mede-ontwerper, niet alleen als uitvoerder.',
    ],
    lquote: 'Zonder podium bouwt deze persoon zijn eigen podium — en dat is zelden binnen dezelfde organisatie.',
    mismatch: [
      'Innovatie roepen maar besluitvorming vertragen.',
      'Bestaande structuren beschermen boven nieuwe mogelijkheden.',
      'Geen strategische dialoog of toekomstbeeld.',
    ],
    energycost: [
      'Geen ruimte voor ideeën.',
      'Trage besluitvorming.',
      'Vastzitten in oude patronen.',
    ],
    wd: [
      'Inspirerende projectruimtes met externe prikkels',
      'Innovatiehubs die toekomstgericht werk zichtbaar maken',
      'Zicht op beweging, buitenwereld en verandering',
    ],
    ls: [
      'Geef strategisch mandaat',
      'Verbind visie aan actie met deadline',
      'Betrek bij de strategische agenda',
    ],
    ct: [
      'Krachtig naast de Presteerder',
      'Kan de Zekerzoeker destabiliseren',
      'Motor van verandering in transitie',
    ],
    cluster: 'creatie',
  },
];

export const QUESTIONS = [
  { q: 'Wat geeft jou de meeste energie op een werkdag?', a: ['Iets nieuws maken of bedenken', 'Een stap zetten in mijn eigen ontwikkeling', 'Een doel halen — met een vinkje erachter', 'Diep in een vraagstuk duiken', 'Een goed gesprek met een collega', 'Samenwerken met mensen die ik vertrouw', 'Weten wat ik vandaag moet doen', 'Een kans zien die anderen nog niet zien'] },
  { q: 'Hoe reageer jij op een plotselinge verandering in je werk?', a: ['Ik zie het als kans om iets nieuws te proberen', 'Ik vraag me af wat ik ervan kan leren', 'Ik wil snel weten wat het voor mijn resultaten betekent', 'Ik wil het eerst goed begrijpen', 'Ik bespreek het eerst met collega\'s', 'Ik hoop dat het mijn team niet uit elkaar trekt', 'Ik word onrustig als er niet snel duidelijkheid is', 'Ik ben blij — stilstand is achteruitgang'] },
  { q: 'Wat ergert jou het meeste op de werkvloer?', a: ['Te veel regels en te weinig vrijheid', 'Geen ruimte om te groeien', 'Vaagheid over wat er van mij verwacht wordt', 'Oppervlakkige besluiten zonder onderbouwing', 'Weinig aandacht voor de mens achter het werk', 'Wisselende teams zonder continuïteit', 'Onverwachte veranderingen zonder uitleg', 'Gebrek aan ambitie of toekomstvisie'] },
  { q: 'Hoe ziet jouw ideale werkdag eruit?', a: ['Vrijheid om zelf vorm te geven aan mijn werk', 'Vol met nieuwe inzichten en uitdagingen', 'Gericht, productief en aan het einde klaar', 'Rustig, diep en zonder onnodige onderbrekingen', 'Goed gesprek, samenwerken, mensen zien', 'Samen met mijn vaste team aan iets werken', 'Helder, overzichtelijk en voorspelbaar', 'Strategie, richting en toekomst'] },
  { q: 'Wat motiveert jou het meest in je werk?', a: ['Iets creëren wat er nog niet was', 'Iedere dag een beetje beter worden', 'Zichtbaar resultaat boeken', 'Diep begrip van hoe iets in elkaar zit', 'Iemand verder helpen of verbinden', 'Deel zijn van een hecht team', 'Weten dat ik betrouwbaar bijdroeg', 'Bijdragen aan iets groters dan vandaag'] },
  { q: 'Welk type omgeving werkt het beste voor jou?', a: ['Open, creatief en flexibel', 'Lerend en uitdagend', 'Resultaatgericht en efficiënt', 'Rustig, geordend en informatierijk', 'Menselijk en sociaal', 'Vertrouwd met dezelfde mensen', 'Stabiel en voorspelbaar', 'Inspirerend en toekomstgericht'] },
  { q: 'Wat vind jij het belangrijkst in een goede samenwerking?', a: ['Ruimte voor eigen ideeën', 'Dat we van elkaar leren', 'Dat we doelen halen', 'Dat besluiten goed onderbouwd zijn', 'Dat iedereen gehoord wordt', 'Dat we op elkaar kunnen rekenen', 'Dat rollen en verwachtingen helder zijn', 'Dat we richting geven aan de toekomst'] },
  { q: 'Wanneer was jij echt in je element?', a: ['Iets gemaakt of bedacht dat werkte', 'Iets geleerd wat ik niet wist', 'Een doel gehaald waar ik hard voor werkte', 'Iets begrepen wat heel complex leek', 'Een samenwerking die echt klikte', 'Het gevoel dat we als team één waren', 'Rust, overzicht en alles op zijn plek', 'Een inzicht dat de richting veranderde'] },
  { q: 'Hoe geef jij het liefst richting aan je eigen werk?', a: ['Zelf bepalen hoe ik het aanpak', 'Mijn eigen groeipunten sturen', 'Sturen op resultaat en voortgang', 'Verdieping en structuur aanbrengen', 'Afstemmen met anderen', 'Samen optrekken in een vast ritme', 'Werken vanuit een helder kader', 'Agenda bepalen op toekomstkansen'] },
  { q: 'Wat maakt een leidinggevende goed in jouw ogen?', a: ['Geeft ruimte en vertrouwen', 'Investeert in mijn ontwikkeling', 'Is duidelijk en resultaatgericht', 'Biedt inhoudelijk houvast', 'Is menselijk en betrokken', 'Houdt het team bij elkaar', 'Communiceert helder en consistent', 'Heeft visie en lef'] },
  { q: 'Wat beschrijft jouw werkstijl het best?', a: ['Creatief en autonoom', 'Lerend en nieuwsgierig', 'Doelgericht en gedisciplineerd', 'Analytisch en grondig', 'Sociaal en empathisch', 'Stabiel en loyaal', 'Gestructureerd en betrouwbaar', 'Visionair en vernieuwend'] },
  { q: 'Wat heeft direct invloed op hoe goed jij werkt?', a: ['Vrijheid om de ruimte zelf in te richten', 'Toegang tot nieuwe kennis en prikkels', 'Een plek zonder afleiding', 'Rust en overzicht om diep te denken', 'Collega\'s en ontmoetingsplekken', 'Een vaste plek met vertrouwd team', 'Duidelijke indeling en weinig verandering', 'Een inspirerende omgeving'] },
  { q: 'Wanneer voel jij je het meest ondergewaardeerd?', a: ['Als ik niet creatief mag zijn', 'Als er geen ruimte is voor groei', 'Als resultaten niet erkend worden', 'Als diepgang niet gewaardeerd wordt', 'Als de menselijke kant genegeerd wordt', 'Als ik buitengesloten ben van de groep', 'Als het onduidelijk is wat ik moet doen', 'Als mijn visie niet serieus genomen wordt'] },
  { q: 'Hoe ga jij om met onzekerheid?', a: ['Ik gebruik het als experimenteerruimte', 'Ik zie het als leerkans', 'Ik zoek houvast in doelen en voortgang', 'Ik analyseer tot het duidelijker is', 'Ik praat erover met anderen', 'Ik zoek steun bij mijn vaste team', 'Ik wacht liever tot het duidelijker is', 'Ik zie het als kans voor verandering'] },
  { q: 'Als je een nieuwe opdracht krijgt — wat is je eerste reactie?', a: ['Hoe pak ik dit aan op mijn manier?', 'Wat kan ik hiervan leren?', 'Wat is het doel en hoe haal ik het?', 'Wat zijn alle kanten van dit vraagstuk?', 'Met wie doe ik dit?', 'Wie zijn mijn teamleden en de rollen?', 'Wat zijn de verwachtingen en de kaders?', 'Welke kans biedt dit voor de toekomst?'] },
  { q: 'Waar haal jij op een moeilijke dag het meeste houvast uit?', a: ['Ruimte om iets te maken of uit te proberen', 'Weten dat ik iets nieuws heb geleerd', 'Een concreet resultaat — hoe klein ook', 'Grip krijgen op wat er speelt', 'Contact met iemand die luistert', 'Steun van mijn vaste team', 'Duidelijkheid over wat er van me verwacht wordt', 'Een groter doel voor ogen houden'] },
];