export const ARCHETYPES = [
  {
    id: 'maker',
    name: 'Maker',
    kw: ['creëren', 'vrijheid', 'experiment'],
    short: 'Jij maakt. Ideeën krijgen voor jou pas echt waarde als je ze kunt omzetten in iets zichtbaars of tastbaars.',
    motivation: 'Vrijheid om te creëren, te experimenteren en snel iets neer te zetten.',
    energy_from: 'Ruimte om iets nieuws te bedenken, te proberen en direct om te zetten in actie.',
    frustration: 'Te veel regels, trage besluitvorming en omgevingen waarin initiatief wordt afgeremd.',
    strengths: 'Brengt creativiteit, energie en beweging. Zet ideeën om in iets concreets.',
    bricks: 'Flexibele werkplekken, creatieve zones, projecttafels, whiteboards en plekken waar je direct kunt maken, schetsen of testen.',
    bricksProfile: {
      focus: 1,
      work: 2,
      hybride: 1,
      meeting: 2,
      project: 4,
      team: 3,
      learning: 2,
      retreat: 1,
      social: 3,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Maker bruikbaar in korte bursts — voor het uitwerken van een concept of het verwerken van feedback. Geen langdurige isolatie, maar gerichte momenten van uitwerking.',
      work: 'Standaard werkplekken zijn voor de Maker acceptabel als ze flexibel zijn en dicht bij creatieve zones liggen. Een vaste bureau zonder maakruimte rondom voelt beperkend.',
      hybride: 'Hybride plekken zijn voor de Maker functioneel maar geen prioriteit. Snel schakelen mag digitaal of fysiek — zolang het het creatieve proces niet vertraagt.',
      meeting: 'Overlegplekken zijn voor de Maker alleen waardevol als ze klein en snel zijn. Een staand overleg van tien minuten werkt beter dan een uur in een vergaderzaal.',
      project: 'Creatieve plekken zijn de kern van de Maker. Whiteboards, projecttafels, prototypemateriaal en ruimte om ideeën zichtbaar te maken — dit is het natuurlijke habitat. Hoe meer ruimte om te maken, hoe beter.',
      team: 'Samenwerkplekken zijn voor de Maker cruciaal als ze actief zijn — grote tafels, schrijfwanden, ruimte om te bewegen. Geen formele vergaderomgevingen maar zones waar iets gemaakt wordt.',
      learning: 'Leerplekken zijn voor de Maker interessant als ze direct toepasbaar zijn. Leren door te doen past beter dan formele leeromgevingen. Informele kenniszones werken het best.',
      retreat: 'Rustplekken zijn voor de Maker een ventiel, geen werkplek. Een korte pauze om de creativiteit te resetten is nuttig maar geen vast onderdeel van het ritme.',
      social: 'Informele plekken zijn voor de Maker een prettige inspiratiebron. Toevallige ontmoeting bij de koffiecorner kan een vastgelopen idee vlot trekken.',
    },
    bytes: 'Lichte, snelle tools die creatie ondersteunen in plaats van vertragen. Denk aan Miro, Figma, notitietools en eenvoudige samenwerkingsplatforms.',
    behavior: 'Geef richting op hoofdlijnen, maar laat ruimte in de aanpak. Deze persona floreert bij vertrouwen, autonomie en experiment.',
    friction: [
      'Strakke procedures drukken jouw energie omlaag.',
      'Te veel controle voelt als wantrouwen.',
      'Als alles eerst besproken moet worden, zakt jouw initiatief weg.',
    ],
    consequence: [
      'Zonder ruimte om te maken, slaat jouw energie om in frustratie.',
      'Je wordt minder zichtbaar als jouw creatiekracht niet wordt benut.',
      'De organisatie verliest vernieuwing zonder dat iemand het meteen merkt.',
    ],
    leadership: [
      'Geef vrijheid binnen duidelijke kaders.',
      'Stuur op resultaat, niet op ieder stapje.',
      'Maak experimenteren normaal en veilig.',
    ],
    lquote: 'Als je deze persoon te strak aanstuurt, raak je niet de chaos kwijt — maar juist de creativiteit.',
    mismatch: [
      'Werkplekken zonder maakruimte of visuele hulpmiddelen.',
      'Culturen waarin conformiteit belangrijker is dan initiatief.',
      'Overleggen zonder ruimte om iets uit te proberen.',
    ],
    energycost: [
      'Te veel regels en controle.',
      'Geen ruimte om ideeën te testen.',
      'Steeds moeten wachten op toestemming.',
    ],
    wd: [
      'Creatieve zones met whiteboards en projecttafels',
      'Flexibele werkplekken die meebewegen met het werk',
      'Ruimte om ideeën zichtbaar te maken',
    ],
    ls: [
      'Geef richting, geen dichtgetimmerde instructie',
      'Beloon initiatief zichtbaar',
      'Maak leren door te doen normaal',
    ],
    ct: [
      'Combineert sterk met de Denker',
      'Botst vaak met de Zekerzoeker',
      'Brengt ideeën en energie in het team',
    ],
    cluster: 'creatie',
  },
  {
    id: 'groeier',
    name: 'Groeier',
    kw: ['leren', 'ontwikkeling', 'vooruit'],
    short: 'Jij groeit. Stilstand voelt voor jou niet veilig, maar juist alsof je energie verliest.',
    motivation: 'Nieuwe dingen leren, jezelf ontwikkelen en steeds een stap verder komen.',
    energy_from: 'Uitdaging, feedback, nieuwe ervaringen en zichtbare ontwikkeling.',
    frustration: 'Herhaling, routine en omgevingen waar weinig ruimte is om te leren of te groeien.',
    strengths: 'Leert snel, beweegt mee en stimuleert ook anderen om zich te ontwikkelen.',
    bricks: 'Leerplekken, duo-werkplekken, informele kenniszones en plekken waar coaching en feedback vanzelf ontstaan.',
    bricksProfile: {
      focus: 2,
      work: 3,
      hybride: 1,
      meeting: 2,
      project: 3,
      team: 2,
      learning: 4,
      retreat: 1,
      social: 2,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Groeier nuttig voor reflectie en verdieping na nieuwe ervaringen. Geen langdurige isolatie maar gerichte verwerkingsmomenten.',
      work: 'Standaard werkplekken zijn voor de Groeier acceptabel zolang er voldoende uitdaging en afwisseling in de omgeving is. Een vaste plek naast uitdagende collega\'s werkt beter dan een stille hoek.',
      hybride: 'Hybride plekken zijn voor de Groeier functioneel maar niet ideaal. De Groeier leert het liefst in fysieke aanwezigheid waar nuance en interactie volledig mogelijk zijn.',
      meeting: 'Overlegplekken zijn voor de Groeier waardevol als het sparren, feedback ontvangen en ideeën toetsen mogelijk maakt. Vergaderen om te vergaderen werkt averechts.',
      project: 'Creatieve plekken spreken de Groeier aan omdat ze ruimte bieden voor experiment en nieuwe aanpakken. Niet als doel op zich maar als leermiddel en inspiratiebron.',
      team: 'Samenwerkplekken zijn voor de Groeier waardevol als leeromgeving. Samenwerken met mensen die anders denken of meer weten geeft energie. Co-creatie en kennisdeling in actie zijn de ideale samenwerkplek.',
      learning: 'Leerplekken zijn de kern van de Groeier. Kennispleinen, coachingsruimtes, plekken voor feedback en uitwisseling — dit is waar de Groeier het beste gedijt. Zichtbare toegang tot inspiratie en nieuwe kennis is essentieel.',
      retreat: 'Rustplekken zijn voor de Groeier nuttig als verwerkingsmoment na intensieve leerervaringen. Even terugkeren op zichzelf voordat de volgende uitdaging begint.',
      social: 'Informele plekken zijn voor de Groeier een bron van toevallige kennisuitwisseling. Spontane gesprekken over werk en inspiratie geven energie en nieuwe ideeën.',
    },
    bytes: 'Tools die ontwikkeling zichtbaar maken, feedback makkelijk maken en nieuwe kennis toegankelijk houden.',
    behavior: 'Geef perspectief, uitdaging en leerkansen. Laat ontwikkeling onderdeel zijn van het werk zelf.',
    friction: [
      'Zonder uitdaging droogt jouw motivatie snel op.',
      'Weinig feedback voelt voor jou als stilstand.',
      'Als ontwikkeling wordt beloofd maar niet waargemaakt, zakt je vertrouwen.',
    ],
    consequence: [
      'Je blijft wel werken, maar niet meer echt groeien.',
      'De kans neemt toe dat je elders op zoek gaat naar ontwikkeling.',
      'Je energie daalt als je geen toekomst meer voelt.',
    ],
    leadership: [
      'Bespreek leerdoelen actief.',
      'Geef uitdagende opdrachten voor routine.',
      'Maak groei zichtbaar en concreet.',
    ],
    lquote: 'Als je deze persoon niet uitdaagt, verlies je eerst de energie — en daarna de persoon.',
    mismatch: [
      'Functies of teams waarin alles hetzelfde blijft.',
      'Een cultuur zonder feedback.',
      'Omgevingen waarin ontwikkelen alleen bij woorden blijft.',
    ],
    energycost: [
      'Routine zonder uitdaging.',
      'Geen feedback krijgen.',
      'Geen ruimte om te groeien.',
    ],
    wd: [
      'Kennispleinen en informele leerzones',
      'Plekken voor coaching, feedback en uitwisseling',
      'Zichtbare toegang tot inspiratie en nieuwe kennis',
    ],
    ls: [
      'Maak leren onderdeel van het werk',
      'Geef groei taal en richting',
      'Zorg voor regelmatige feedback',
    ],
    ct: [
      'Versterkt de Presteerder goed',
      'Kan Zekerzoekers onrustig maken',
      'Brengt ontwikkeling en beweging in teams',
    ],
    cluster: 'creatie',
  },
  {
    id: 'presteerder',
    name: 'Presteerder',
    kw: ['resultaat', 'tempo', 'grip'],
    short: 'Jij gaat voor resultaat. Je krijgt energie van voortgang, scherpte en iets echt afmaken.',
    motivation: 'Doelen halen, voortgang zien en grip houden op wat ertoe doet.',
    energy_from: 'Heldere doelen, zichtbare voortgang, focus en tastbaar resultaat.',
    frustration: 'Onduidelijkheid, uitstel, eindeloos overleg en teams zonder scherpte.',
    strengths: 'Brengt focus, tempo en resultaat. Helpt teams om niet te blijven hangen.',
    bricks: 'Focusplekken, afgeschermde werkzones, projectruimtes zonder ruis en plekken waar voortgang zichtbaar is.',
    bricksProfile: {
      focus: 4,
      work: 2,
      hybride: 2,
      meeting: 1,
      project: 3,
      team: 1,
      learning: 1,
      retreat: 1,
      social: 1,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn de absolute kern voor de Presteerder. Diepe focuszones zonder ruis, onderbreking of visuele afleiding zijn geen luxe maar noodzaak. Hier wordt het meeste werk gedaan en de meeste energie teruggewonnen.',
      work: 'Standaard werkplekken zijn voor de Presteerder acceptabel mits ze rustig, ergonomisch en goed uitgerust zijn. Zekerheid over beschikbaarheid op piekdagen is essentieel — geen hot-desking.',
      hybride: 'Hybride plekken zijn voor de Presteerder functioneel en efficiënt. Snel schakelen zonder reistijd past goed bij het resultaatgerichte werkritme, mits de technische kwaliteit goed is.',
      meeting: 'Overlegplekken zijn voor de Presteerder tijdverlies tenzij ze leiden tot een helder besluit. Klein, functioneel en snel beschikbaar — geen grote vergaderzalen voor routineoverleg.',
      project: 'Creatieve plekken spreken de Presteerder weinig aan. Experiment zonder richting voelt als tijdverlies. Alleen interessant als er een concreet doel en een helder resultaat aan vastzit.',
      team: 'Samenwerkplekken zijn voor de Presteerder alleen waardevol als ze resultaatgericht zijn. Gerichte projectomgevingen met zichtbare voortgang en een duidelijk doel passen goed.',
      learning: 'Leerplekken zijn voor de Presteerder relevant als ze direct bijdragen aan betere prestaties. Geen leren om het leren — wel leren om scherper, sneller of effectiever te worden.',
      retreat: 'Rustplekken zijn voor de Presteerder functioneel als herstelmoment. Kort opladen om daarna weer volledig gefocust verder te kunnen — niet meer dan dat.',
      social: 'Informele plekken kosten de Presteerder eerder energie dan dat ze iets opleveren, tenzij het gesprek inhoudelijk en doelgericht is. Toevallig bijkletsen is geen prioriteit.',
    },
    bytes: 'Dashboards, taaktools, planningstools en systemen die direct inzicht geven in doelen, deadlines en voortgang.',
    behavior: 'Wees duidelijk over doelen, verwachtingen en prioriteiten. Geef ruimte, maar houd richting scherp.',
    friction: [
      'Onduidelijkheid remt jouw tempo direct af.',
      'Vergaderen zonder besluit voelt als energieverlies.',
      'Steeds wisselende prioriteiten kosten vertrouwen.',
    ],
    consequence: [
      'Je haakt mentaal af als resultaat te lang uitblijft.',
      'Je levert dan nog wel, maar niet meer op jouw topniveau.',
      'De drive zakt als er geen scherpte meer is.',
    ],
    leadership: [
      'Wees direct en helder.',
      'Erken resultaat expliciet.',
      'Maak prioriteiten zichtbaar en stabiel.',
    ],
    lquote: 'Zonder helder doel gaat deze motor draaien — maar nergens naartoe.',
    mismatch: [
      'Werkplekken zonder focus.',
      'Culturen waarin proces belangrijker is dan resultaat.',
      'Langdurige vaagheid over richting.',
    ],
    energycost: [
      'Onduidelijke doelen.',
      'Vergaderen zonder besluit.',
      'Geen plek voor focus.',
    ],
    wd: [
      'Diepe focuszones',
      'Visuele voortgangsborden',
      'Projectplekken dicht bij stille werkplekken',
    ],
    ls: [
      'Maak prioriteiten concreet',
      'Erken voortgang en output',
      'Stuur op uitkomst, niet op drukte',
    ],
    ct: [
      'Sterk naast de Vernieuwer',
      'Kan botsen met de Verbinder',
      'Houdt teams scherp en in beweging',
    ],
    cluster: 'executie',
  },
  {
    id: 'denker',
    name: 'Denker',
    kw: ['analyse', 'diepgang', 'inhoud'],
    short: 'Jij denkt eerst, dan doe je. Je wilt begrijpen hoe iets werkelijk in elkaar zit voordat je beweegt.',
    motivation: 'Complexiteit doorgronden en kwaliteit brengen op basis van inzicht.',
    energy_from: 'Rust, diepgang, analyse en de ruimte om een vraagstuk echt te begrijpen.',
    frustration: 'Oppervlakkigheid, haast en besluiten zonder inhoudelijke basis.',
    strengths: 'Brengt diepgang, scherpte en kwaliteit. Ziet wat anderen missen.',
    bricks: 'Stille concentratieplekken, focuskamers, bibliotheekachtige zones en omgevingen met zo min mogelijk ruis.',
    bricksProfile: {
      focus: 4,
      work: 3,
      hybride: 1,
      meeting: 1,
      project: 1,
      team: 1,
      learning: 2,
      retreat: 3,
      social: 1,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Denker de meest essentiële werkplek van alle archetypes. Volledig stille, afgesloten zones zonder visuele of auditieve prikkels zijn geen pretje maar een basisvoorwaarde voor goed functioneren.',
      work: 'Standaard werkplekken zijn voor de Denker alleen acceptabel als ze rustig genoeg zijn. Open kantoorlandschappen met veel beweging en geluid zijn een cognitieve belasting. Een vaste, stille plek geeft houvast.',
      hybride: 'Hybride plekken zijn voor de Denker functioneel als de technische kwaliteit goed is. De optie om vanuit rust deel te nemen zonder fysiek aanwezig te zijn in een drukke ruimte wordt gewaardeerd.',
      meeting: 'Overlegplekken zijn voor de Denker uitputtend tenzij het overleg inhoudelijk goed voorbereid is. Spontaan overleg of vergaderen zonder scherpe vraag kost disproportioneel veel energie.',
      project: 'Creatieve plekken passen de Denker alleen als er rust en structuur in zitten. Open rommelige makerspaces werken averechts. Een stille analyseplek met whiteboard voor complexe vraagstukken is de uitzondering die werkt.',
      team: 'Samenwerkplekken zijn voor de Denker alleen zinvol als ze inhoudelijk en goed voorbereid zijn. Geen open brainstormsessies maar gestructureerde werkvormen met een scherpe inhoudelijke vraag.',
      learning: 'Leerplekken zijn voor de Denker waardevol mits ze diepgang bieden. Zelfstudie, toegang tot documentatie en kennisstructuren die verdieping mogelijk maken passen uitstekend.',
      retreat: 'Rustplekken zijn voor de Denker even essentieel als concentratieplekken. Na intensief denkwerk is herstel noodzakelijk. Een stille terugtrekplek buiten het zicht van anderen is geen luxe maar een noodzaak.',
      social: 'Informele plekken zijn voor de Denker eerder een bron van ruis dan van energie. Toevallig contact is welkom als het inhoudelijk is — informeel bijkletsen kost meer dan het oplevert.',
    },
    bytes: 'Logische systemen, goede documentatie, complete informatie en tools die verdieping ondersteunen.',
    behavior: 'Geef denktijd, inhoud en voorbereiding. Kwaliteit gaat hier vóór snelheid.',
    friction: [
      'Open kantoren zijn voor jou vaak cognitieve ruis.',
      'Besluiten zonder analyse voelen onveilig.',
      'Te veel onderbrekingen maken je minder sterk.',
    ],
    consequence: [
      'Je trekt je terug als diepgang geen plek krijgt.',
      'Jouw inhoudelijke bijdrage verdwijnt stil uit beeld.',
      'Kwaliteit zakt zonder dat het direct zichtbaar is.',
    ],
    leadership: [
      'Geef informatie op tijd en volledig.',
      'Respecteer denktijd.',
      'Waardeer grondigheid zichtbaar.',
    ],
    lquote: 'Wie deze persoon haast, verliest vaak precies datgene wat de kwaliteit bewaakt.',
    mismatch: [
      'Werkvloeren met continue ruis.',
      'Culturen waar snelheid belangrijker is dan inhoud.',
      'Onvoorbereide overleggen zonder scherpe vraag.',
    ],
    energycost: [
      'Onderbrekingen.',
      'Besluiten zonder analyse.',
      'Te weinig rust om te verdiepen.',
    ],
    wd: [
      'Stille focusplekken en akoestische rust',
      'Heldere informatievoorziening',
      'Plekken waar concentratie beschermd wordt',
    ],
    ls: [
      'Geef tijd om te denken',
      'Zorg voor goede voorbereiding',
      'Bescherm kwaliteit in het proces',
    ],
    ct: [
      'Versterkt de Maker goed',
      'Kan met de Presteerder schuren op tempo',
      'Brengt kwaliteit en diepte in teams',
    ],
    cluster: 'reflectie',
  },
  {
    id: 'verbinder',
    name: 'Verbinder',
    kw: ['mensen', 'contact', 'samenhang'],
    short: 'Jij verbindt. Voor jou ontstaat goed werk pas echt als mensen zich gezien en verbonden voelen.',
    motivation: 'Menselijk contact, samenwerking en een sfeer waarin mensen elkaar echt vinden.',
    energy_from: 'Ontmoeting, samenwerking, afstemming en betekenisvol contact.',
    frustration: 'Isolement, afstand, sfeerbreuk en werken zonder echte verbinding.',
    strengths: 'Brengt mensen samen, voelt de onderstroom aan en houdt samenwerking menselijk.',
    bricks: 'Ontmoetingsplekken, koffiecorners, open samenwerkzones en routing die toevallige ontmoeting stimuleert.',
    bricksProfile: {
      focus: 1,
      work: 1,
      hybride: 2,
      meeting: 3,
      project: 2,
      team: 3,
      learning: 1,
      retreat: 1,
      social: 4,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Verbinder functioneel maar geen bron van energie. Langdurig alleen werken in stilte kost meer dan het oplevert. Korte focusmomenten zijn prima — geen dagvullend patroon.',
      work: 'Standaard werkplekken zijn voor de Verbinder acceptabel als ze dicht bij het team zijn en spontaan contact mogelijk maken. Geïsoleerde werkplekken ver van de looproutes werken averechts.',
      hybride: 'Hybride plekken zijn voor de Verbinder functioneel maar niet ideaal. Online contact voelt dunner dan fysiek. Goede hybride technologie vermindert dit gemis maar heft het niet op.',
      meeting: 'Overlegplekken zijn voor de Verbinder essentieel — maar dan plekken die echt contact mogelijk maken. Geen kille vergaderzalen maar omgevingen die uitnodigen tot gesprek, oogcontact en echte verbinding.',
      project: 'Creatieve plekken zijn voor de Verbinder interessant als ze samenwerken faciliteren. Samen iets maken of bedenken geeft energie — solo creatief werk minder.',
      team: 'Samenwerkplekken zijn voor de Verbinder de kern. Open, toegankelijke zones die spontane samenwerking uitlokken en ruimte bieden voor relatie én taak zijn het ideale werkklimaat.',
      learning: 'Leerplekken zijn voor de Verbinder het meest waardevol als ze sociaal zijn. Samen leren, kennisdelen en van elkaar horen passen uitstekend — zelfstudie in isolatie past minder goed.',
      retreat: 'Rustplekken zijn voor de Verbinder zelden een bewuste keuze. Als de Verbinder zich terugtrekt, is dat een signaal dat iets niet klopt in de samenwerking of sfeer — geen normaal patroon.',
      social: 'Informele plekken zijn de kern van de Verbinder. Warme ontmoetingszones, koffiecorners en routing die toevallig contact uitlokt zijn geen bijzaak maar het hart van de werkomgeving voor dit archetype.',
    },
    bytes: 'Communicatietools die menselijk voelen en echt contact makkelijk maken.',
    behavior: 'Maak ruimte voor contact, relatie en afstemming. Verbinding is geen bijzaak maar voorwaarde.',
    friction: [
      'Te veel digitale afstand kost je energie.',
      'Een koude, taakgerichte sfeer maakt je minder sterk.',
      'Als ontmoeting geen plek krijgt, droogt samenwerking op.',
    ],
    consequence: [
      'Je ziet vaak als eerste waar het schuurt.',
      'Zonder verbinding wordt het team stiller en afstandelijker.',
      'Belangrijke signalen worden gemist als jij geen ruimte krijgt.',
    ],
    leadership: [
      'Maak bewust tijd voor contact.',
      'Betrek deze persona vroeg bij verandering.',
      'Zorg dat ontmoeting mogelijk en normaal is.',
    ],
    lquote: 'Een team zonder verbinder merkt pas wat er ontbreekt als iedereen nog wel samenwerkt, maar niemand meer verbonden is.',
    mismatch: [
      'Werkplekken die alleen op focus zijn ingericht.',
      'Teams die alleen digitaal contact hebben.',
      'Culturen waar relatie ondergeschikt is aan taak.',
    ],
    energycost: [
      'Alleen werken zonder contact.',
      'Geen ruimte voor gesprek.',
      'Te veel afstand in samenwerking.',
    ],
    wd: [
      'Warme ontmoetingszones',
      'Informele overlegplekken',
      'Routing die spontane ontmoeting ondersteunt',
    ],
    ls: [
      'Vraag hoe het echt gaat',
      'Maak ontmoeting onderdeel van het werk',
      'Gebruik deze persona als signaalgever',
    ],
    ct: [
      'Sterk naast de Teamspeler',
      'Kan schuren met de Presteerder',
      'Bewaakt de menselijke kant van samenwerking',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'teamspeler',
    name: 'Teamspeler',
    kw: ['loyaliteit', 'vertrouwen', 'samen winnen'],
    short: 'Jij werkt voor het team. Voor jou telt niet alleen wat jij bereikt, maar vooral wat jullie samen neerzetten.',
    motivation: 'Bijdragen aan een vaste groep met vertrouwen, continuïteit en gezamenlijk succes.',
    energy_from: 'Samenwerken met bekende mensen, duidelijke rollen en een sterk teamgevoel.',
    frustration: 'Wisselende teams, onduidelijke verhoudingen en gebrek aan loyaliteit.',
    strengths: 'Brengt rust, loyaliteit en samenwerking. Houdt teams bij elkaar.',
    bricks: 'Vaste teamplekken, herkenbare zones en omgevingen waarin een team zich echt als team kan organiseren.',
    bricksProfile: {
      focus: 1,
      work: 3,
      hybride: 2,
      meeting: 3,
      project: 1,
      team: 4,
      learning: 1,
      retreat: 1,
      social: 2,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Teamspeler acceptabel mits ze dicht bij het team zijn. Werken in een volledig geïsoleerde focusruimte ver van het team voelt onbehaaglijk. Een rustige plek binnen het teamgebied werkt beter.',
      work: 'Standaard werkplekken zijn voor de Teamspeler ideaal als ze vast en herkenbaar zijn. Een vaste plek in het team, altijd beschikbaar — dit geeft houvast en versterkt het teamgevoel. Geen hot-desking.',
      hybride: 'Hybride plekken zijn voor de Teamspeler functioneel mits het team er goed mee overweg kan. Teamcohesie moet ook op afstand bewaakt worden — duidelijke hybride afspraken zijn essentieel.',
      meeting: 'Overlegplekken zijn voor de Teamspeler essentieel — maar dan vaste, herkenbare plekken die bij het team horen. Een vaste teamoverlegplek die teamrituelen en continuïteit ondersteunt werkt beter dan wisselende vergaderzalen.',
      project: 'Creatieve plekken zijn voor de Teamspeler interessant als het team er samen gebruik van maakt. Solo creatief werk in een creatieve zone past minder goed bij dit archetype.',
      team: 'Samenwerkplekken zijn de kern van de Teamspeler. Vaste teamzones met herkenbare inrichting en rituelen werken beter dan wisselende open samenwerkruimtes. Continuïteit en vertrouwdheid zijn de basis.',
      learning: 'Leerplekken zijn voor de Teamspeler relevant als ze teamgericht zijn. Gezamenlijk leren en kennisdelen binnen het team past beter dan individuele leertrajecten.',
      retreat: 'Rustplekken zijn voor de Teamspeler zelden een bewuste keuze. Als de Teamspeler zich terugtrekt, is dat een teken van discomfort met de teamdynamiek — niet een normaal werkpatroon.',
      social: 'Informele plekken zijn voor de Teamspeler waardevol als ze teamgericht zijn. Gezamenlijke lunch, vaste koffieplek voor het team en rituelen verankerd in de ruimte geven energie en versterken het teamgevoel.',
    },
    bytes: 'Gedeelde systemen, teamoverzichten, vaste processen en tools die samenwerking voorspelbaar maken.',
    behavior: 'Werk met ritme, helderheid en gezamenlijke afspraken. Deze persona floreert in continuïteit.',
    friction: [
      'Wisselende teams voelen als structurele onrust.',
      'Geen thuisbasis maakt jou minder stevig.',
      'Te weinig aandacht voor teamgevoel maakt jouw kracht onzichtbaar.',
    ],
    consequence: [
      'Je loyaliteit neemt af als het teamfundament ontbreekt.',
      'Onrust vertaalt zich in lagere betrokkenheid.',
      'De samenhang verdwijnt als continuïteit ontbreekt.',
    ],
    leadership: [
      'Wees voorspelbaar en consistent.',
      'Kondig veranderingen op tijd aan.',
      'Maak teamdynamiek bespreekbaar.',
    ],
    lquote: 'Als je het team als wisselgeld behandelt, verliest deze persoon zijn fundament.',
    mismatch: [
      'Hot-desking en continu wisselende groepen.',
      'Een cultuur waarin iedereen vooral voor zichzelf werkt.',
      'Te veel reorganisatie zonder bedding.',
    ],
    energycost: [
      'Wisselende teams.',
      'Geen vaste basis.',
      'Onzekerheid in samenwerking.',
    ],
    wd: [
      'Vaste teamplekken',
      'Herkenbare zones voor teams',
      'Rituelen en routines verankerd in de ruimte',
    ],
    ls: [
      'Bescherm teamcontinuïteit',
      'Zorg voor duidelijkheid in rollen',
      'Betrek het team in veranderingen',
    ],
    ct: [
      'Sterk naast de Verbinder',
      'Kan onrustig worden van de Vernieuwer',
      'Brengt stabiliteit in samenwerking',
    ],
    cluster: 'verbinding',
  },
  {
    id: 'zekerzoeker',
    name: 'Zekerzoeker',
    kw: ['structuur', 'rust', 'duidelijkheid'],
    short: 'Jij zorgt dat het klopt. Duidelijkheid, structuur en voorspelbaarheid maken jou sterk.',
    motivation: 'Overzicht, stabiliteit en weten waar je aan toe bent.',
    energy_from: 'Heldere verwachtingen, structuur, rust en een voorspelbare omgeving.',
    frustration: 'Chaos, last-minute wijzigingen en onduidelijkheid.',
    strengths: 'Brengt rust, betrouwbaarheid en proceskwaliteit. Ziet snel waar het niet klopt.',
    bricks: 'Vaste werkplekken, duidelijke zones, overzichtelijke routing en zo min mogelijk onnodige verandering.',
    bricksProfile: {
      focus: 3,
      work: 4,
      hybride: 2,
      meeting: 1,
      project: 1,
      team: 2,
      learning: 1,
      retreat: 2,
      social: 1,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Zekerzoeker essentieel — bij voorkeur vaste, herkenbare plekken die elke dag beschikbaar zijn. Geen zoekwerk, geen onzekerheid over beschikbaarheid. Voorspelbaarheid is de sleutel.',
      work: 'Standaard werkplekken zijn voor de Zekerzoeker de belangrijkste werkplek. Een vaste plek die altijd beschikbaar is, ergonomisch goed ingericht en dicht bij bekende collega\'s. Geen hot-desking — zekerheid over de eigen plek is een basisvoorwaarde.',
      hybride: 'Hybride plekken zijn voor de Zekerzoeker functioneel mits de technische afspraken helder en stabiel zijn. Onduidelijkheid over wie online is en wie fysiek aanwezig geeft spanning.',
      meeting: 'Overlegplekken zijn voor de Zekerzoeker alleen energiegevend als het overleg goed voorbereid en gestructureerd is. Spontane vergaderingen of overleggen zonder agenda kosten disproportioneel veel energie.',
      project: 'Creatieve plekken passen de Zekerzoeker slecht. Rommeligheid, experiment en onduidelijkheid over wat er verwacht wordt zijn het tegenovergestelde van wat energie geeft.',
      team: 'Samenwerkplekken zijn voor de Zekerzoeker acceptabel als de spelregels helder zijn. Wie zit waar, wat is het doel, hoe lang duurt het — als dat duidelijk is werkt samenwerken prima. Zonder structuur kost het te veel energie.',
      learning: 'Leerplekken zijn voor de Zekerzoeker interessant als ze structuur bieden. Georganiseerde kennissessies en stap-voor-stap leertrajecten passen beter dan open experimentele leeromgevingen.',
      retreat: 'Rustplekken zijn voor de Zekerzoeker een essentiële buffer bij onzekerheid of hoge werkdruk. Een vaste terugtrekplek die altijd beschikbaar is geeft houvast en zekerheid.',
      social: 'Informele plekken zijn voor de Zekerzoeker prettig in kleine, vertrouwde kring. Grote open ontmoetingszones met veel onbekenden geven eerder spanning dan energie.',
    },
    bytes: 'Heldere systemen, stabiele processen en betrouwbare informatie.',
    behavior: 'Communiceer vroeg, helder en consistent. Deze persona heeft voorspelbaarheid nodig om goed te functioneren.',
    friction: [
      'Onduidelijkheid is voor jou geen kleine irritatie, maar een echte blokkade.',
      'Last-minute wijzigingen kosten jou disproportioneel veel energie.',
      'Te veel verandering tegelijk haalt jouw stabiliteit weg.',
    ],
    consequence: [
      'Chronische onduidelijkheid leidt tot spanning.',
      'Je levert minder goed als je steeds moet schakelen zonder houvast.',
      'Weerstand groeit als helderheid verdwijnt.',
    ],
    leadership: [
      'Communiceer vroeg en volledig.',
      'Maak verwachtingen expliciet.',
      'Bied structuur in onzekere periodes.',
    ],
    lquote: 'Onduidelijkheid is voor deze persoon geen uitdaging, maar een aantasting van werkvermogen.',
    mismatch: [
      'Omgevingen met continue verandering.',
      'Vage verwachtingen of incomplete informatie.',
      'Werkplekken zonder vaste ankers.',
    ],
    energycost: [
      'Onvoorspelbaarheid.',
      'Te veel verandering.',
      'Onduidelijke kaders.',
    ],
    wd: [
      'Vaste ankerplekken',
      'Rustige, overzichtelijke inrichting',
      'Duidelijke structuren en voorspelbare zones',
    ],
    ls: [
      'Geef helderheid vroeg',
      'Behandel structuur als kwaliteit',
      'Respecteer de behoefte aan voorspelbaarheid',
    ],
    ct: [
      'Sterke basis naast de Presteerder',
      'Botst vaak met de Maker',
      'Brengt rust en betrouwbaarheid',
    ],
    cluster: 'structuur',
  },
  {
    id: 'vernieuwer',
    name: 'Vernieuwer',
    kw: ['vooruitdenken', 'kansen', 'verandering'],
    short: 'Jij ziet wat anders kan. Voor jou is verandering niet vooral risico, maar vooral potentie.',
    motivation: 'Kansen zien, beweging creëren en bouwen aan iets dat beter kan.',
    energy_from: 'Nieuwe ideeën, beweging, verandering en een blik op de toekomst.',
    frustration: 'Stilstand, behoudzucht en organisaties zonder visie.',
    strengths: 'Brengt richting, vernieuwing en toekomstgericht denken.',
    bricks: 'Inspirerende werkplekken, innovatiezones, projectruimtes en omgevingen die beweging en vernieuwing zichtbaar maken.',
    bricksProfile: {
      focus: 1,
      work: 1,
      hybride: 2,
      meeting: 2,
      project: 4,
      team: 3,
      learning: 3,
      retreat: 1,
      social: 2,
    },
    bricksProfileText: {
      focus: 'Concentratieplekken zijn voor de Vernieuwer zelden de plek waar de beste ideeën ontstaan. Te veel stilte en structuur dempen het vooruitdenkende denken. Korte focusmomenten zijn functioneel voor uitwerking — niet de motor.',
      work: 'Standaard werkplekken zijn voor de Vernieuwer acceptabel als ze flexibel en inspirerend zijn. Een vaste saai bureau in een routineuze omgeving werkt remmend. Plekken die toekomstdenken normaliseren zijn beter.',
      hybride: 'Hybride plekken zijn voor de Vernieuwer functioneel en efficiënt. Snel schakelen met mensen overal past goed bij het brede netwerk dat dit archetype onderhoudt.',
      meeting: 'Overlegplekken zijn voor de Vernieuwer waardevol als het overleg strategisch en toekomstgericht is. Operationeel bijpraten kost energie — visiegesprekken en strategische sessies geven energie.',
      project: 'Creatieve plekken zijn de kern van de Vernieuwer. Innovatiezones, experimenteerruimtes en omgevingen die beweging en vernieuwing normaliseren zijn het ideale habitat. Hoe meer ruimte voor experiment en toekomstgericht denken, hoe beter.',
      team: 'Samenwerkplekken zijn voor de Vernieuwer essentieel als ze gericht zijn op strategie en verkenning. Grote open innovatiezones waar ideeën kunnen botsen en nieuwe richtingen zichtbaar worden zijn het ideale samenwerkklimaat.',
      learning: 'Leerplekken zijn voor de Vernieuwer interessant als ze toegang geven tot nieuwe kennis, trends en toekomstgericht denken. Niet voor het oppoetsen van bestaande vaardigheden maar voor het verkennen van nieuwe richtingen.',
      retreat: 'Rustplekken zijn voor de Vernieuwer een functionele reset — niet meer dan dat. Een korte pauze om daarna met hernieuwde energie vooruit te kijken. Geen structureel onderdeel van het werkpatroon.',
      social: 'Informele plekken zijn voor de Vernieuwer interessant als ze kruisbestuiving mogelijk maken. Contact met mensen van buiten het eigen team of de eigen organisatie geeft de meeste energie en nieuwe ideeën.',
    },
    bytes: 'Tools voor innovatie, experimenteren, trends en snelle iteratie.',
    behavior: 'Geef ruimte voor ideeën, strategie en verkenning. Betrek deze persona in verandering en koers.',
    friction: [
      'Sturen op alleen de korte termijn knelt voor jou direct.',
      'Bureaucratie voelt voor jou als energielek.',
      'Als ideeën nooit landen, stop jij met delen.',
    ],
    consequence: [
      'Je wordt stiller als vernieuwing geen podium krijgt.',
      'De organisatie verliest zicht op toekomstige kansen.',
      'Jouw energie verschuift naar plekken waar wel beweging is.',
    ],
    leadership: [
      'Geef strategische ruimte.',
      'Verbind visie aan concrete experimenten.',
      'Zie deze persona als mede-ontwerper.',
    ],
    lquote: 'Zonder podium bouwt deze persoon zijn eigen podium — en dat is zelden binnen dezelfde organisatie.',
    mismatch: [
      'Omgevingen zonder ruimte voor vernieuwing.',
      'Besluitvorming die vernieuwing steeds vertraagt.',
      'Culturen zonder toekomstperspectief.',
    ],
    energycost: [
      'Geen ruimte voor ideeën.',
      'Trage besluitvorming.',
      'Vastzitten in oude patronen.',
    ],
    wd: [
      'Inspirerende innovatiezones',
      'Plekken waar toekomstgericht werk zichtbaar is',
      'Ruimte voor experiment en beweging',
    ],
    ls: [
      'Geef visie en mandaat',
      'Verbind ideeën aan actie',
      'Gebruik deze persona bij strategie en transitie',
    ],
    ct: [
      'Sterk naast de Presteerder',
      'Kan Zekerzoekers destabiliseren',
      'Motor van verandering in teams',
    ],
    cluster: 'creatie',
  },
];

export const QUESTIONS = [
  {
    q: 'Wat geeft jou op een gewone werkdag de meeste energie?',
    a: [
      'Iets nieuws bedenken en meteen beginnen — ook zonder compleet plan',
      'Merken dat ik iets nieuws heb geleerd of beter ben geworden',
      'Iets echt afmaken en het resultaat zien',
      'Me volledig vastbijten in een ingewikkeld vraagstuk',
      'Een goed gesprek of oprechte verbinding met iemand',
      'Samenwerken met mensen op wie ik kan bouwen',
      'Rust, duidelijkheid en weten precies wat er van mij verwacht wordt',
      'Een kans zien die anderen nog niet zien en daar iets mee doen',
    ],
  },
  {
    q: 'Hoe ziet jouw ideale manier van werken eruit?',
    a: [
      'Vrij, creatief en op mijn eigen manier — zonder te veel kaders',
      'Lerend en groeiend — ik wil steeds beter worden in wat ik doe',
      'Doelgericht en scherp — van A naar B, zo efficiënt mogelijk',
      'Verdiepend en inhoudelijk — eerst begrijpen, dan handelen',
      'Mensgericht — met aandacht voor sfeer, gevoel en verbinding',
      'Samen met een vaste groep mensen die ik goed ken en vertrouw',
      'Gestructureerd en voorspelbaar — ik werk best met duidelijke kaders',
      'Vernieuwend en toekomstgericht — ik denk liever vooruit dan achteruit',
    ],
  },
  {
    q: 'Wat kost jou op het werk de meeste energie?',
    a: [
      'Regels, procedures en weinig ruimte om iets zelf te proberen',
      'Herhaling, routine en geen kans om te groeien',
      'Veel praten maar weinig bereiken — overleg zonder besluit',
      'Oppervlakkigheid en besluiten die niet inhoudelijk kloppen',
      'Werken zonder echt contact — koud, taakgericht en afstandelijk',
      'Steeds wisselende teams en geen stabiel teamgevoel',
      'Chaos, vage afspraken en last-minute veranderingen',
      'Stilstand — vasthouden aan hoe het altijd is gegaan',
    ],
  },
  {
    q: 'Welke zin past het best bij hoe jij in je werk staat?',
    a: [
      'Ik maak het liefst iets wat er nog niet was',
      'Ik wil altijd een stapje verder komen dan gisteren',
      'Ik ben op mijn best als ik ergens naartoe werk',
      'Ik wil iets echt begrijpen voordat ik handel',
      'Ik ben het meest mezelf als ik goed contact heb met mensen',
      'Ik ben sterk als ik weet dat het team op mij rekent',
      'Ik functioneer het best als ik weet waar ik aan toe ben',
      'Ik zie altijd mogelijkheden die anderen over het hoofd zien',
    ],
  },
  {
    q: 'Hoe neem jij een beslissing als het er echt op aankomt?',
    a: [
      'Ik volg mijn gevoel, maak een keuze en stuur onderweg bij',
      'Ik kijk wat ik hiervan kan leren en wat de volgende stap is',
      'Ik kies wat het meeste oplevert en ga er meteen voor',
      'Ik analyseer alle kanten totdat ik zeker weet wat klopt',
      'Ik stem af met anderen en voel wat er nodig is',
      'Ik kijk wat het beste is voor het team als geheel',
      'Ik kies voor de meest duidelijke en voorspelbare optie',
      'Ik kijk welke kans of nieuwe richting er in de beslissing zit',
    ],
  },
  {
    q: 'Wanneer voelt werk voor jou echt waardevol?',
    a: [
      'Als ik iets heb gemaakt dat er eerst nog niet was',
      'Als ik merk dat ik gegroeid ben of iets nieuws heb geleerd',
      'Als ik een concreet doel heb gehaald waar ik naartoe heb gewerkt',
      'Als ik iets complex echt heb doorgrond en begrepen',
      'Als er oprecht contact was en mensen zich gezien voelden',
      'Als we als team iets hebben neergezet waar we trots op zijn',
      'Als er rust, overzicht en duidelijkheid was de hele dag',
      'Als ik een nieuwe kans of richting heb zien ontstaan',
    ],
  },
  {
    q: 'Je krijgt een nieuwe opdracht. Wat is jouw eerste reactie?',
    a: [
      'Ik begin meteen — ideeën komen vanzelf als ik in beweging ben',
      'Ik vraag me af wat ik hiervan kan leren',
      'Ik wil eerst weten wat het doel is en wanneer het klaar moet zijn',
      'Ik wil alle context en achtergrond begrijpen voordat ik begin',
      'Ik zoek eerst afstemming — wie is erbij betrokken en hoe voelen zij erbij?',
      'Ik kijk eerst met wie ik dit samen doe en wat ieders rol is',
      'Ik wil weten wat de kaders zijn en wat er precies van mij verwacht wordt',
      'Ik kijk meteen welke nieuwe mogelijkheid of richting hierin zit',
    ],
  },
  {
    q: 'Welke werkomgeving haalt het beste in jou naar boven?',
    a: [
      'Een omgeving met ruimte, vrijheid en tools om te maken en experimenteren',
      'Een omgeving die uitdaagt, inspireert en leerruimte biedt',
      'Een omgeving gericht op focus, tempo en resultaat — zonder ruis',
      'Een rustige, stille omgeving waar ik me echt kan concentreren',
      'Een warme omgeving met menselijk contact en echte ontmoeting',
      'Een vertrouwde, stabiele plek met een vaste groep mensen',
      'Een overzichtelijke omgeving met duidelijke structuur en voorspelbaarheid',
      'Een inspirerende omgeving waar vernieuwing en toekomstdenken normaal zijn',
    ],
  },
  {
    q: 'Wat maakt samenwerking voor jou echt goed?',
    a: [
      'Dat ik ruimte krijg voor mijn eigen ideeën en aanpak',
      'Dat we van elkaar leren en elkaar uitdagen om te groeien',
      'Dat we tempo maken, scherp zijn en echt iets neerzetten',
      'Dat besluiten inhoudelijk kloppen en niet worden afgeraffeld',
      'Dat er oprechte aandacht is voor de mens achter het werk',
      'Dat we op elkaar kunnen rekenen en het team centraal staat',
      'Dat rollen, verwachtingen en afspraken voor iedereen helder zijn',
      'Dat we samen ergens naartoe bewegen en richting geven aan iets nieuws',
    ],
  },
  {
    q: 'Wat maakt een team voor jou uiteindelijk minder goed?',
    a: [
      'Dat initiatieven direct worden dichtgeregeld of tegengehouden',
      'Dat niemand zich ontwikkelt of iets nieuws probeert te leren',
      'Dat er veel wordt gepraat maar weinig concreet wordt afgemaakt',
      'Dat snelheid belangrijker wordt dan inhoud en kwaliteit',
      'Dat de menselijke kant volledig wordt genegeerd',
      'Dat iedereen vooral voor zichzelf werkt in plaats van samen',
      'Dat afspraken vaag blijven of voortdurend veranderen',
      'Dat vernieuwing steeds wordt tegengehouden door oude gewoonten',
    ],
  },
  {
    q: 'Er komt een grote verandering in jouw organisatie. Wat is jouw eerste gedachte?',
    a: [
      'Interessant — wat kan ik hier mee en hoe zet ik dit in beweging?',
      'Wat kan ik hiervan leren en hoe maak ik mezelf sterker?',
      'Wat betekent dit voor mijn doelen en planning?',
      'Ik wil eerst begrijpen wat er precies verandert en waarom',
      'Wat doet dit met de mensen om mij heen?',
      'Wat betekent dit voor ons team en onze samenwerking?',
      'Gaat dit goed komen? Ik wil weten waar ik aan toe ben',
      'Eindelijk beweging — dit biedt kansen die ik wil benutten',
    ],
  },
  {
    q: 'Wat houdt jou op de lange termijn gemotiveerd in je werk?',
    a: [
      'Vrijheid om dingen op mijn manier te doen en te creëren',
      'Het gevoel dat ik steeds verder kom en mezelf blijf ontwikkelen',
      'Voortgang zien, grip houden en resultaten boeken',
      'Inhoud, inzicht en het gevoel dat kwaliteit ertoe doet',
      'Betekenisvol contact en het gevoel erbij te horen',
      'Een sterk team met echte saamhorigheid en gedeelde verantwoordelijkheid',
      'Zekerheid, duidelijkheid en weten waar ik aan toe ben',
      'Het gevoel dat ik bijdraag aan iets nieuws en toekomstgericht',
    ],
  },
  {
    q: 'Wat voegt jouw aanwezigheid toe aan een team?',
    a: [
      'Ik zet ideeën in beweging en maak dingen concreet',
      'Ik breng energie, nieuwsgierigheid en leerbereidheid',
      'Ik houd het team scherp op doelen en resultaten',
      'Ik bewaak de kwaliteit en diepgang van besluiten',
      'Ik zorg dat mensen zich gezien en verbonden voelen',
      'Ik houd het team bij elkaar en zorg voor saamhorigheid',
      'Ik breng structuur, betrouwbaarheid en overzicht',
      'Ik zie kansen en geef richting aan wat er anders of beter kan',
    ],
  },
  {
    q: 'Wat heb jij nodig van een leidinggevende om op je best te zijn?',
    a: [
      'Vertrouwen en ruimte om dingen op mijn eigen manier aan te pakken',
      'Oprechte aandacht voor mijn groei en ontwikkeling',
      'Heldere doelen, scherpe prioriteiten en directe communicatie',
      'Inhoudelijke voorbereiding en de ruimte om goed na te denken',
      'Menselijke betrokkenheid en het gevoel dat ik ertoe doe',
      'Stabiliteit, aandacht voor het team en consistentie',
      'Helderheid, voorspelbaarheid en duidelijke afspraken vooraf',
      'Visie, lef en ruimte om nieuwe richtingen te verkennen',
    ],
  },
  {
    q: 'Je rijdt naar huis. Wanneer denk je: dit was een goede dag?',
    a: [
      'Als ik iets heb gemaakt of echt in beweging heb gezet',
      'Als ik iets nieuws heb geleerd of een stap verder ben gekomen',
      'Als ik concreet resultaat heb geboekt en iets echt af is',
      'Als ik een ingewikkeld vraagstuk echt heb doorgrond',
      'Als er oprecht contact was en ik me verbonden voelde',
      'Als we het als team samen goed hebben gedaan',
      'Als er de hele dag rust, overzicht en duidelijkheid was',
      'Als ik een nieuwe kans of richting heb zien ontstaan',
    ],
  },
  {
    q: 'Kies de zin die het meest bij jou past als je eerlijk bent:',
    a: [
      'Ik werk het best als ik vrij ben om te creëren en te experimenteren',
      'Ik werk het best als ik leer en mezelf steeds ontwikkel',
      'Ik werk het best als ik weet wat het doel is en er naartoe kan werken',
      'Ik werk het best als ik de tijd krijg om iets echt te doordenken',
      'Ik werk het best als er oprecht contact is en mensen elkaar zien',
      'Ik werk het best in een vertrouwd team met duidelijke rollen',
      'Ik werk het best als alles helder, overzichtelijk en voorspelbaar is',
      'Ik werk het best als er ruimte is voor vernieuwing en nieuwe ideeën',
    ],
  },
];